parameter_mapping = {
    "TC_Messbereich": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_Nennmass": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_ObAbmass": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_UntAbmass": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_Einheit": {'einheit': '', 'übersetzung': '', 'kategorie': ''},
    "TC_Messwert": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_MesskraftME": {'einheit': 'N', 'übersetzung': '', 'kategorie': ''},
    "TC_MesskraftSchwankungME": {'einheit': 'N', 'übersetzung': '', 'kategorie': ''},
    "TC_TempME": {'einheit': '°C', 'übersetzung': '', 'kategorie': ''},
    "TC_TempMO": {'einheit': '°C', 'übersetzung': '', 'kategorie': ''},
    "TC_TempEN": {'einheit': '°C', 'übersetzung': '', 'kategorie': ''},
    "TC_AusdehnKoeffME": {'einheit': '1/°K', 'übersetzung': '', 'kategorie': ''},
    "TC_AusdehnKoeffMO": {'einheit': '1/°K', 'übersetzung': '', 'kategorie': ''},
    "TC_AusdehnKoeffEN": {'einheit': '1/°K', 'übersetzung': '', 'kategorie': ''},
    "TC_DurchmesserMessflaeche": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_DurchmesserMesseinsatzME": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_BreiteMessflaecheMO": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_BreiteMessflaecheEN": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_FaktorKennlinieME": {'einheit': '', 'übersetzung': '', 'kategorie': ''},
    "TC_ParameterKennlinieME": {'einheit': 'µm', 'übersetzung': '', 'kategorie': ''},
    "TC_NichtLinearKennlinieME": {'einheit': 'µm', 'übersetzung': '', 'kategorie': ''},
    "TC_MantellinieMO": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_MantellinieME": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_MantellinieEN": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_NennmassEN": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_ZeitDeltaMessungEN_MO": {'einheit': 'min', 'übersetzung': '', 'kategorie': ''},
    "TC_ZeitDrift": {'einheit': 'µm/min', 'übersetzung': '', 'kategorie': ''},
    "TC_DurchmesserEN": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_Winkelabweichung_von_90_Grad": {'einheit': '°', 'übersetzung': '', 'kategorie': ''},
    "TC_Radius_der_Zone_des_Spiels": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_Laenge_kurze_Kante_PEM": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_Tol_Abw_Spanne_ISO_3650": {'einheit': 'µm', 'übersetzung': '', 'kategorie': ''},
    "TC_Elast_Modul_Normal": {'einheit': 'N/m²', 'übersetzung': '', 'kategorie': ''},
    "TC_Elast_Modul_MO": {'einheit': 'N/m²', 'übersetzung': '', 'kategorie': ''},
    "TC_Poisson_Koeff_Normal": {'einheit': '', 'übersetzung': '', 'kategorie': ''},
    "TC_Poisson_Koeff_MO": {'einheit': '', 'übersetzung': '', 'kategorie': ''},
    "TC_Korrelationskoeffizient": {'einheit': '', 'übersetzung': '', 'kategorie': ''},
    "TC_Schrittweite_Geradheitskalibrierung_EN": {'einheit': 'mm', 'übersetzung': '2043 Schrittweite bei der Geradheitskalibrierung des EN', 'kategorie': ''},
    "TC_Positionsgenauigkeit_Kalibrierung_MO": {'einheit': 'mm', 'übersetzung': '2044 Positionsgenauigkeit bei Kalibrierung des MO', 'kategorie': ''},
    "TC_Betrag_max_Abweichung_Bezugsgerade": {'einheit': 'µm', 'übersetzung': '2045 Betrag der maximalen Abweichung von der Bezugsgerade', 'kategorie': ''},
    "TC_Laenge_stehender_Schenkel_EN": {'einheit': 'mm', 'übersetzung': '2046 Länge des stehenden Schenkels (EN)', 'kategorie': ''},
    "TC_Abstand_Stuetzpunkte_EN": {'einheit': 'mm', 'übersetzung': '2047 Abstand der Stützpunkte am EN', 'kategorie': ''},
    "TC_Geradheit_Messplatte_EN": {'einheit': 'µm', 'übersetzung': '2048 Geradheit der Messplatte im Bereich des EN', 'kategorie': ''},
    "TC_Positionsabweichung_Stuetzpunkte_EN": {'einheit': 'mm', 'übersetzung': '2049 Positionsabweichung der Stützpunkte des EN', 'kategorie': ''},
    "TC_Kalibrierung_Geradheit_EN": {'einheit': 'µm', 'übersetzung': '2050 Kalibrierung der Geradheit des EN', 'kategorie': ''},
    "TC_Laenge_stehender_Schenkel_MO": {'einheit': 'mm', 'übersetzung': '2051 Länge des stehenden Schenkels des MO', 'kategorie': ''},
    "TC_Stuetzpunktabstand_MO": {'einheit': 'mm', 'übersetzung': '2052 Stützpunktabstand des MO', 'kategorie': ''},
    "TC_Geradheit_Messplatte_MO": {'einheit': 'µm', 'übersetzung': '2053 Geradheit der Messplatte im Bereich des MO', 'kategorie': ''},
    "TC_Positionsabweichung_Stuetzpunkte_MO": {'einheit': 'mm', 'übersetzung': '2054 Positionsabweichung der Stützpunkte des MO', 'kategorie': ''},
    "TC_Kalibrierung_Geradheit_MO": {'einheit': 'µm', 'übersetzung': '2055 Kalibrierung der Geradheit des MO', 'kategorie': ''},
    "TC_Kalibrierung_Ebenheit_Messplatte": {'einheit': 'µm', 'übersetzung': '2056 Kalibrierung der Ebenheit der Messplatte', 'kategorie': ''},
    "TC_Positionsgenauigkeit_Stuetzpunkte": {'einheit': 'mm', 'übersetzung': '2058 Positionsgenauigkeit der Stützpunkte', 'kategorie': ''},
    "TC_Schrittweite_Geradheitskalibrierung_MO": {'einheit': 'mm', 'übersetzung': '2059 Schrittweite bei Geradheitskalibrierung des MO', 'kategorie': ''},
    "TC_Hoehendifferenz_Stuetzpunkte": {'einheit': 'mm', 'übersetzung': '2060 H÷hendifferenz der Stützpunkte', 'kategorie': ''},
    "TC_Laenge_Messobjekt": {'einheit': 'mm', 'übersetzung': '2061 Länge des Messobjekts', 'kategorie': ''},
    "TC_Anzahl_Verschiebungen_MO": {'einheit': '', 'übersetzung': '2065 Anzahl der Verschiebungen des MO', 'kategorie': ''},
    "TC_Messbereichsendwert_Messeinrichtung": {'einheit': 'mm', 'übersetzung': '2066 Messbereichsendwert der Messeinrichtung', 'kategorie': ''},
    "TC_Hoehe_zu_Rechtwinkligkeit": {'einheit': 'mm', 'übersetzung': '2067 Zur Rechtwinkligkeit geh÷rende H÷he', 'kategorie': ''},
    "TC_Rh_Anzahl_Messwerte_pro_Teilmessstrecke": {'einheit': '', 'übersetzung': '2068 Anzahl Messwerte pro Teilmessstrecke', 'kategorie': ''},
    "TC_Rh_Anzahl_Teilmessstrecken": {'einheit': '', 'übersetzung': '2069 Anzahl  Teilmessstrecken', 'kategorie': ''},
    "TC_Rh_Ortabhaengige_Unsicherheit_in_y": {'einheit': 'mm', 'übersetzung': '2070 Ortsabhängige Unsicherheit in y-Richtung', 'kategorie': ''},
    "TC_Rh_Gradient_in_Rillenrichtung": {'einheit': 'µm/mm', 'übersetzung': '2071 Gradient in Rillenrichtung', 'kategorie': ''},
    "TC_Rh_Messpunktabstand": {'einheit': 'µm', 'übersetzung': '2072 Messpunktabstand', 'kategorie': ''},
    "TC_Rh_Tiefpasswellenlaengen": {'einheit': 'µm', 'übersetzung': '2073 Tiefpasswellenlängen', 'kategorie': ''},
    "TC_Rh_Kennwertaenderungsfaktor": {'einheit': '', 'übersetzung': '2074 Tastspitzenabhängige Kennwertänderung', 'kategorie': ''},
    "TC_Rh_Gemessene_Kenngroesse": {'einheit': 'µm', 'übersetzung': '2075 Gemessener Kennwert', 'kategorie': ''},
    "TC_Rh_Anzahl_Wiederholungsmessungen_geaenderter_Antastort": {'einheit': '', 'übersetzung': '2076 Anzahl Wiederholmessungen bei unterschiedlichen Antastorten', 'kategorie': ''},
    "TC_Rh_Anzahl_Wiederholmessungen_selber_Antastort": {'einheit': '', 'übersetzung': '2077 Anzahl Wiederholmessungen am selben Antastort', 'kategorie': ''},
    "TC_Fm_Anzahl_Wiederholmessungen_StreuungAnzeige": {'einheit': '', 'übersetzung': '2078 Anzahl Messungen (Streuung der Anzeige)', 'kategorie': ''},
    "TC_Fm_Abstand_zwischen_zwei_benachbarten_Profilpunkten": {'einheit': 'µm', 'übersetzung': '2079 Abstand zwischen zwei benachbarten Profilpunkten', 'kategorie': ''},
    "TC_Fm_Grenzwellenlaenge": {'einheit': 'µm', 'übersetzung': '2080 Grenzwellenlänge', 'kategorie': ''},
    "TC_Fm_Messwert_MO": {'einheit': 'µm', 'übersetzung': '2081 Richtiger Wert des Vergr÷ßerungsnormals', 'kategorie': ''},
    "TC_Fm_Richtiger_Wert_Rundheit_Kugelnormal": {'einheit': 'µm', 'übersetzung': '2082 Richtiger Wert der Rundheit des Kugelnormals', 'kategorie': ''},
    "TC_Fm_Messunsicherheit_der_Kalibrierung_Kugelnormal": {'einheit': 'µm', 'übersetzung': '2083 Messunsicherheit der Kalibrierung von Kugelnormal', 'kategorie': ''},
    "TC_Fm_Gemessenden_Exzentrizitaet": {'einheit': 'mm', 'übersetzung': '2084 Gemessenden Exzentrizität', 'kategorie': ''},
    "TC_Fm_Aussendurchmesser_MO": {'einheit': 'mm', 'übersetzung': '2085 Außendurchmesser des MO', 'kategorie': ''},
    "TC_Fm_Tastkugeldurchmesser": {'einheit': 'mm', 'übersetzung': '2086 Tastkugeldurchmesser', 'kategorie': ''},
    "TC_Fm_Innendurchmesser_MO": {'einheit': 'mm', 'übersetzung': '2087 Innendurchmesser des MO', 'kategorie': ''},
    "TC_Fm_Kippung_MO_XAchse": {'einheit': 'µm/10mm', 'übersetzung': '2088 Kippung des MO zu X-Achse', 'kategorie': ''},
    "TC_Fm_Kippung_MO_YAchse": {'einheit': 'µm/10mm', 'übersetzung': '2089 Kippung des MO zu Y-Achse', 'kategorie': ''},
    "TC_Fm_Radius_MO": {'einheit': 'mm', 'übersetzung': '2090', 'kategorie': ''},
    "TC_Fm_Neigung_Zylinderachse_MO_zu_Flaeche_XOY": {'einheit': 'Grad', 'übersetzung': '2091 Neigung der Zylinderachse des MO zu Fläche XOY', 'kategorie': ''},
    "TC_Fm_Formabweichung_Normal": {'einheit': 'µm', 'übersetzung': '2092 Formabweichung des Normals', 'kategorie': ''},
    "TC_Fm_Kalibrierung_Normal": {'einheit': 'µm', 'übersetzung': '2093 Kalibrierung des Normals (Messunsicherheit)', 'kategorie': ''},
    "TC_Fm_Standardabweichung_Wiederholmessungen_Normal": {'einheit': 'µm', 'übersetzung': '2094 Standardabweichung der Wiederholmessungen des Normals', 'kategorie': ''},
    "TC_Fm_AnzahlMessungen_Fuehrungsabweichung": {'einheit': '', 'übersetzung': '2095 Anzahl Messungen (Führungabweichung)', 'kategorie': ''},
    "TC_Fm_Gemessene_Rundheit_EN": {'einheit': 'µm', 'übersetzung': '2096 Gemessene Rundheit des Kugelnormals (EN)', 'kategorie': ''},
    "TC_Gewinde_Steigung": {'einheit': 'mm', 'übersetzung': '2097 Gewindesteigung', 'kategorie': ''},
    "TC_KTMG_Gemessener_Abstand": {'einheit': 'mm', 'übersetzung': '2101 Gemessener Abstand (< 100 mm)', 'kategorie': ''},
    "TC_KTMG_Konstanter_Anteil_EMPE": {'einheit': 'µm', 'übersetzung': '2102 Konstanter Anteil A des Grenzwerts E(MPE) der Längenmessabw.', 'kategorie': ''},
    "TC_KTMG_Anzahl_Messpunkte": {'einheit': '', 'übersetzung': '2103 Anzahl der Messpunkte', 'kategorie': ''},
    "TC_KTMG_Gemessener_Winkel": {'einheit': 'Grad', 'übersetzung': '2104 Gemessener Winkel', 'kategorie': ''},
    "TC_KTMG_Laenge_kleinster_Schenkel": {'einheit': 'mm', 'übersetzung': '2105 Länge des kleinsten Schenkels (kleiner 100 mm)', 'kategorie': ''},
    "TC_KTMG_Gemessene_Geradheit": {'einheit': 'µm', 'übersetzung': '2106 Gemessene Geradheit', 'kategorie': ''},
    "TC_KTMG_Sektor_Kreis": {'einheit': 'Grad', 'übersetzung': '2107 Kreisabschnitt', 'kategorie': ''},
    "TC_3d_KMG_A": {'einheit': '', 'übersetzung': '2301 Konstanter Teil A des Grenzwertes MPE(E) der Längenmessabw.', 'kategorie': '5'},
    "TC_3d_KMG_K": {'einheit': '', 'übersetzung': '2302 Faktor K des Grenzwertes der Längenmeßabw. MPE(E)=(A+L/K) µm', 'kategorie': '5'},
    "TC_3d_KMG_LT": {'einheit': 'mm', 'übersetzung': '2340 Tasterlänge für spezifizierte Mehrfachtaster-Lageabweichung (LT)', 'kategorie': '5'},
    "TC_3d_KMG_Uc": {'einheit': 'µm', 'übersetzung': '2303 Kalibrierunsicherheit des Kugelnormal-Durchmessers (µm) - U(C)', 'kategorie': '5'},
    "TC_3d_KMG_alphaM": {'einheit': '10-6/K', 'übersetzung': '2304 Ausdehnungskoeffizient der KMG-Maßstäbe (10-6/K) - Alpha M', 'kategorie': '5'},
    "TC_3d_KMG_MPEML": {'einheit': 'µm', 'übersetzung': '2357 Grenzwert für Mehrtaster-Lageabweichung MPE(ML)', 'kategorie': '5'},
    "TC_3d_KMG_Tm": {'einheit': '°C', 'übersetzung': '2305 Mittlere Temperatur der KMG-Maßstäbe (°C) - tM', 'kategorie': '4'},
    "TC_3d_KMG_deltaTm": {'einheit': 'K', 'übersetzung': '2306 Max. Abweichung von der mittleren Temperatur (K) - Maßstab', 'kategorie': '4'},
    "TC_3d_KMG_alphaW": {'einheit': '10-6/K', 'übersetzung': '2307 Ausdehnungskoeffizient des Werkstücks (10-6/K)', 'kategorie': '4'},
    "TC_3d_KMG_Tw": {'einheit': '°C', 'übersetzung': '2308 Mittlere Temperatur des Werkstücks (°C)', 'kategorie': '4'},
    "TC_3d_KMG_deltaTw": {'einheit': 'K', 'übersetzung': '2309 Max. Abweichung von der mittleren Temperatur (K) - Werkstück', 'kategorie': '4'},
    "TC_3d_DUME_D": {'einheit': 'mm', 'übersetzung': '2310 Nennmaß des Durchmessers (D)', 'kategorie': '1'},
    "TC_3d_DUME_alpha": {'einheit': '°', 'übersetzung': '2311 Winkelbereich der Meßpunkte am Umfang (Standard 360°)', 'kategorie': '1'},
    "TC_3d_DUME_l": {'einheit': 'mm', 'übersetzung': '2312 Zylinder: Länge des Formelements (Gesamtlänge bis Rand)', 'kategorie': '1'},
    "TC_3d_DUME_LM": {'einheit': 'mm', 'übersetzung': '2341 Kegel: Messlänge (Bereich der Messpunkte)', 'kategorie': '1'},
    "TC_3d_FORM_L": {'einheit': 'mm', 'übersetzung': '2313 Nennmaß der Länge (gr÷ßere Länge) (L)', 'kategorie': '1'},
    "TC_3d_FORM_DL": {'einheit': 'mm', 'übersetzung': '2314 Nennmaß der Breite (kleinere Länge) (l)', 'kategorie': '1'},
    "TC_3d_FORM_F": {'einheit': 'µm', 'übersetzung': '2315 Formabweichung am Normal aufgrund der Tasterbiegung (µm)', 'kategorie': '3'},
    "TC_3d_FORM_FN": {'einheit': 'µm', 'übersetzung': '2359 Formabweichung (Rundheit) am Normal aus Zertifikat F(N)', 'kategorie': '2'},
    "TC_3d_FORM_FKMG": {'einheit': 'µm', 'übersetzung': '2360 Formabweichung (Rundheit) am Normal aus Messung F(KMG)', 'kategorie': '2'},
    "TC_3d_ABST_L": {'einheit': 'mm', 'übersetzung': '2316 Nennmaß des Abstandes (bei Position theoretischens Maß)', 'kategorie': '1'},
    "TC_3d_ABST_LM1": {'einheit': 'mm', 'übersetzung': '2317 Messlänge am tolerierten Element (Bereich der Messpunkte) - L(ME)', 'kategorie': '1'},
    "TC_3d_ABST_LE1": {'einheit': 'mm', 'übersetzung': '2318 Abstand des Schwerpunktes von der Nullebene -  L(SE)', 'kategorie': '1'},
    "TC_3d_ABST_LM2": {'einheit': 'mm', 'übersetzung': '2319 Messlänge am Bezugselement (Bereich der Messpunkte) - L(MB)', 'kategorie': '1'},
    "TC_3d_ABST_LE2": {'einheit': 'mm', 'übersetzung': '2320 Abstand des Schwerpunktes von der Nullebene - L(SB)', 'kategorie': '1'},
    "TC_3D_ABST_LTE": {'einheit': 'mm', 'übersetzung': '2343 Tasterlänge E  L(TE)', 'kategorie': '3'},
    "TC_3D_ABST_LTB": {'einheit': 'mm', 'übersetzung': '2344 Tasterlänge B  L(TB)', 'kategorie': '3'},
    "TC_3d_Ri_LA": {'einheit': 'mm', 'übersetzung': '2321 Kleinster Abstand des tolerierten Elements vom Bezugselement - L(A)', 'kategorie': '1'},
    "TC_3d_Ri_Alpha": {'einheit': '°', 'übersetzung': '2322 Nennwert des Winkels (in Grad) - Alpha', 'kategorie': '1'},
    "TC_3d_Ri_LME": {'einheit': 'mm', 'übersetzung': '2323 Messlänge am tolerierten Element (Bereich der Messpunkte)- L(ME)', 'kategorie': '1'},
    "TC_3d_Ri_LE": {'einheit': 'mm', 'übersetzung': '2324 Auswertelänge (Länge des tolerierten Elements) - L(E)', 'kategorie': '1'},
    "TC_3d_Ri_LMB": {'einheit': 'mm', 'übersetzung': '2325 Messlänge am Bezugselements (Bereich der Messpunkte) - L(MB)', 'kategorie': '1'},
    "TC_3d_Ri_LTE1": {'einheit': 'mm', 'übersetzung': '2345 Tasterlänge 1 L(TE1)', 'kategorie': '3'},
    "TC_3d_Ri_LTE2": {'einheit': 'mm', 'übersetzung': '2346 Tasterlänge 2 L(TE2)', 'kategorie': '3'},
    "TC_3d_Ri_LTB1": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_3d_Ri_LTB2": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_3d_Sym_DE": {'einheit': 'mm', 'übersetzung': '2326 Breite bzw. Durchmesser des tolerierten Elements - D(E)', 'kategorie': '1'},
    "TC_3d_Sym_LE": {'einheit': 'mm', 'übersetzung': '2327 Länge des tolerierten Elements - L(E)', 'kategorie': '1'},
    "TC_3d_Sym_LME": {'einheit': 'mm', 'übersetzung': '2349 Messlänge am tolerierten Element (Bereich der Messpunkte) - L(ME)', 'kategorie': '1'},
    "TC_3d_Sym_DB": {'einheit': 'mm', 'übersetzung': '2328 Breite bzw. Durchmesser des Bezugselements - D(B)', 'kategorie': '1'},
    "TC_3d_Sym_LB": {'einheit': 'mm', 'übersetzung': '2350 Länge des Bezugselements (Länge bis zum Rand) - L(B)', 'kategorie': '1'},
    "TC_3d_Sym_LMB": {'einheit': 'mm', 'übersetzung': '2329 Messlänge des Bezugselements (Bereich der Messpunkte) - L(MB)', 'kategorie': '1'},
    "TC_3d_Sym_LTE": {'einheit': 'mm', 'übersetzung': '2351 Tasterlänge E L(TE)', 'kategorie': '3'},
    "TC_3d_Sym_LTB": {'einheit': 'mm', 'übersetzung': '2352 Tasterlänge B L(TB)', 'kategorie': '3'},
    "TC_3d_Koax_DE": {'einheit': 'mm', 'übersetzung': '2330 Durchmesser des tolerierten Elements - D(E)', 'kategorie': '1'},
    "TC_3d_Koax_LE": {'einheit': 'mm', 'übersetzung': '2331 Länge des tolerierten Elements - L(E)', 'kategorie': '1'},
    "TC_3d_Koax_LA": {'einheit': 'mm', 'übersetzung': '2332 Gr÷ßter Abstand des tol. Elements zur Mitte des Bezugselements-L(A)', 'kategorie': '1'},
    "TC_3d_Koax_DB": {'einheit': 'mm', 'übersetzung': '2333 Gr÷ßter Durchmesser des Bezugselements - D(B)', 'kategorie': '1'},
    "TC_3d_Koax_LB": {'einheit': 'mm', 'übersetzung': '2334 Länge des Bezugselements (Gesamtlänge bis zum Rand) -  L(B)', 'kategorie': '1'},
    "TC_3d_Koax_LMB": {'einheit': 'mm', 'übersetzung': '2335 Messlänge am Bezugselement (Bereich der Messpunkte) - L(MB)', 'kategorie': '1'},
    "TC_3d_Koax_LME": {'einheit': 'mm', 'übersetzung': '2353 Messlänge am tolerierten Element (Bereich der Messpunkte) - L(ME)', 'kategorie': '1'},
    "TC_3d_Koax_LT": {'einheit': 'mm', 'übersetzung': '2354 -', 'kategorie': ''},
    "TC_3d_Koax_LTB": {'einheit': 'mm', 'übersetzung': '2355 Tasterlänge B- L(TB)', 'kategorie': '3'},
    "TC_3d_Koax_LTE": {'einheit': 'mm', 'übersetzung': '2356 Tasterlänge E- L(TE)', 'kategorie': '3'},
    "TC_3d_KoaxGA_DE": {'einheit': 'mm', 'übersetzung': '2336 Durchmesser des tolerierten Elements - D(E)', 'kategorie': '1'},
    "TC_3d_KoaxGA_LME": {'einheit': 'mm', 'übersetzung': '2337 Messlänge am tolerierten Element (Bereich der Messpunkte) L(ME)', 'kategorie': '1'},
    "TC_3d_KoaxGA_LE": {'einheit': 'mm', 'übersetzung': '2338 Auswertelänge am tolerierten Element (Länge bis zum Rand) - L(E)', 'kategorie': '1'},
    "TC_3d_KoaxGA_LB": {'einheit': 'mm', 'übersetzung': '2339 Bezugslänge (Mittenabstand der beiden Bezugselemente) - L(E)', 'kategorie': '1'},
    "TC_3d_KoaxGA_LA": {'einheit': 'mm', 'übersetzung': '!!! siehe oben  TC_3d_Koax_LA\t2332\tGr÷ßter Abstand des tol. Elements zur Mitte des Bezugselements-L(A)', 'kategorie': '1'},
    "TC_3d_KoaxGA_LTB": {'einheit': 'mm', 'übersetzung': '!!!=  TC_3d_Koax_LTB\t2355\tTasterlänge B- L(TB)', 'kategorie': '3'},
    "TC_3d_KoaxGA_LTE": {'einheit': 'mm', 'übersetzung': '!!!= TC_3d_Koax_LTE\t2356\tTasterlänge E- L(TE)', 'kategorie': '3'},
    "TC_3D_NennLaenge_LD": {'einheit': 'mm', 'übersetzung': '2358\tNennmaß der Länge bzw. Durchmessers L(D)', 'kategorie': '1'},
    "TC_3d_KMG_AUFLOES": {'einheit': '°', 'übersetzung': '', 'kategorie': ''},
    "TC_3d_PktPkt_dist": {'einheit': 'mm', 'übersetzung': '', 'kategorie': ''},
    "TC_3d_PktPkt_Wechsel": {'einheit': 'ja/nein', 'übersetzung': 'Tasterwechsel', 'kategorie': '3'},
    "TC_3d_PktPkt_nTastBe": {'einheit': '', 'übersetzung': 'Anzahl Antastungen Bezugselement', 'kategorie': '2'},
    "TC_3d_PktPkt_nTastTe": {'einheit': '', 'übersetzung': 'Anzahl Antastungen toleriertes Element', 'kategorie': '2'},
    "TC_3d_PktPkt_SigBe": {'einheit': 'mm', 'übersetzung': 'Standardabweichung bei Antastung des BE', 'kategorie': '2'},
    "TC_3d_PktPkt_SigTe": {'einheit': 'mm', 'übersetzung': 'Standardabweichung bei Antastung des TE', 'kategorie': '2'},
    "TC_3d_PktPkt_ScanKgl": {'einheit': 'Grad', 'übersetzung': 'Bereich zum Scannen von Kugeln', 'kategorie': '1'},
    "TC_3d_PktPkt_MBe": {'einheit': 'W/L', 'übersetzung': 'Maximale Harmonik des Profils des BE . Apriori', 'kategorie': ''},
    "TC_3d_PktPkt_Mte": {'einheit': 'W/L', 'übersetzung': 'Maximale Harmonik des Profils des BE . Apriori', 'kategorie': ''},
    "TC_3d_PktPkt_Temp": {'einheit': '°C', 'übersetzung': 'Raumtemperatur', 'kategorie': '4'},
    "TC_3d_PktPkt_Gamma0": {'einheit': 'mm', 'übersetzung': 'Koeff fόr ZufAbw aufgrund Winkel de Sektor', 'kategorie': ''},
    "TC_3d_PktPkt_Gamma1": {'einheit': 'Grad', 'übersetzung': 'Koeff fόr ZufAbw aufgrund Winkel de Sektor', 'kategorie': ''},
    "TC_3d_PktPkt_WinkelSeg_BE": {'einheit': 'Grad', 'übersetzung': 'Winkel Antastbereich (Segment) BE', 'kategorie': '1'},
    "TC_3d_PktPkt_WinkelSeg_TE": {'einheit': 'Grad', 'übersetzung': 'Winkel Antastbereich (Segment) tolerirtes Element', 'kategorie': '1'},
    "TC_3d_PktPkt_AnzSims": {'einheit': '', 'übersetzung': 'Anzahl Simulationen pro Messpunkt', 'kategorie': ''},
    "TC_3d_PktPkt_Dia_BE": {'einheit': 'mm', 'übersetzung': 'Durchmesser Kreis 1 BE', 'kategorie': '1'},
    "TC_3d_PktPkt_Dia_TE": {'einheit': 'mm', 'übersetzung': 'Durchmesser Kreis 2 BE', 'kategorie': '1'},
    "TC_3d_KMG_AmpX": {'einheit': 'mm', 'übersetzung': 'Amplidude Streuung X', 'kategorie': ''},
    "TC_3d_KMG_AmpY": {'einheit': 'mm', 'übersetzung': 'Amplidude Streuung Y', 'kategorie': ''},
}
