export const tcMapping: Record<number, {
  key: string,
  einheit: string,
  übersetzung: string,
  kategorie: number
}> = {
  1: { key: "TC_Messbereich", einheit: "mm", übersetzung: "", kategorie: 0 },
  2: { key: "TC_Nennmass", einheit: "mm", übersetzung: "", kategorie: 0 },
  4: { key: "TC_ObAbmass", einheit: "mm", übersetzung: "", kategorie: 0 },
  3: { key: "TC_UntAbmass", einheit: "mm", übersetzung: "", kategorie: 0 },
  5: { key: "TC_Einheit", einheit: "", übersetzung: "", kategorie: 0 },
  25: { key: "TC_Messwert", einheit: "mm", übersetzung: "", kategorie: 0 },
  26: { key: "TC_MesskraftME", einheit: "N", übersetzung: "", kategorie: 0 },
  27: { key: "TC_MesskraftSchwankungME", einheit: "N", übersetzung: "", kategorie: 0 },
  30: { key: "TC_TempME", einheit: "°C", übersetzung: "", kategorie: 0 },
  31: { key: "TC_TempMO", einheit: "°C", übersetzung: "", kategorie: 0 },
  32: { key: "TC_TempEN", einheit: "°C", übersetzung: "", kategorie: 0 },
  6: { key: "TC_AusdehnKoeffME", einheit: "1/°K", übersetzung: "", kategorie: 0 },
  8: { key: "TC_AusdehnKoeffMO", einheit: "1/°K", übersetzung: "", kategorie: 0 },
  7: { key: "TC_AusdehnKoeffEN", einheit: "1/°K", übersetzung: "", kategorie: 0 },
  9: { key: "TC_DurchmesserMessflaeche", einheit: "mm", übersetzung: "", kategorie: 0 },
  10: { key: "TC_DurchmesserMesseinsatzME", einheit: "mm", übersetzung: "", kategorie: 0 },
  11: { key: "TC_BreiteMessflaecheMO", einheit: "mm", übersetzung: "", kategorie: 0 },
  13: { key: "TC_BreiteMessflaecheEN", einheit: "mm", übersetzung: "", kategorie: 0 },
  14: { key: "TC_FaktorKennlinieME", einheit: "", übersetzung: "", kategorie: 0 },
  15: { key: "TC_ParameterKennlinieME", einheit: "µm", übersetzung: "", kategorie: 0 },
  16: { key: "TC_NichtLinearKennlinieME", einheit: "µm", übersetzung: "", kategorie: 0 },
  22: { key: "TC_MantellinieMO", einheit: "mm", übersetzung: "", kategorie: 0 },
  21: { key: "TC_MantellinieME", einheit: "mm", übersetzung: "", kategorie: 0 },
  24: { key: "TC_MantellinieEN", einheit: "mm", übersetzung: "", kategorie: 0 },
  28: { key: "TC_NennmassEN", einheit: "mm", übersetzung: "", kategorie: 0 },
  33: { key: "TC_ZeitDeltaMessungEN_MO", einheit: "min", übersetzung: "", kategorie: 0 },
  34: { key: "TC_ZeitDrift", einheit: "µm/min", übersetzung: "", kategorie: 0 },
  35: { key: "TC_DurchmesserEN", einheit: "mm", übersetzung: "", kategorie: 0 },
  36: { key: "TC_Winkelabweichung_von_90_Grad", einheit: "°", übersetzung: "", kategorie: 0 },
  37: { key: "TC_Radius_der_Zone_des_Spiels", einheit: "mm", übersetzung: "", kategorie: 0 },
  38: { key: "TC_Laenge_kurze_Kante_PEM", einheit: "mm", übersetzung: "", kategorie: 0 },
  39: { key: "TC_Tol_Abw_Spanne_ISO_3650", einheit: "µm", übersetzung: "", kategorie: 0 },
  40: { key: "TC_Elast_Modul_Normal", einheit: "N/m²", übersetzung: "", kategorie: 0 },
  41: { key: "TC_Elast_Modul_MO", einheit: "N/m²", übersetzung: "", kategorie: 0 },
  42: { key: "TC_Poisson_Koeff_Normal", einheit: "", übersetzung: "", kategorie: 0 },
  43: { key: "TC_Poisson_Koeff_MO", einheit: "", übersetzung: "", kategorie: 0 },
  44: { key: "TC_Korrelationskoeffizient", einheit: "", übersetzung: "", kategorie: 0 },
  45: { key: "TC_Schrittweite_Geradheitskalibrierung_EN", einheit: "mm", übersetzung: " Schrittweite bei der Geradheitskalibrierung des EN", kategorie: 0 },
  46: { key: "TC_Positionsgenauigkeit_Kalibrierung_MO", einheit: "mm", übersetzung: " Positionsgenauigkeit bei Kalibrierung des MO", kategorie: 0 },
  47: { key: "TC_Betrag_max_Abweichung_Bezugsgerade", einheit: "µm", übersetzung: " Betrag der maximalen Abweichung von der Bezugsgerade", kategorie: 0 },
  48: { key: "TC_Laenge_stehender_Schenkel_EN", einheit: "mm", übersetzung: " Länge des stehenden Schenkels (EN)", kategorie: 0 },
  49: { key: "TC_Abstand_Stuetzpunkte_EN", einheit: "mm", übersetzung: " Abstand der Stützpunkte am EN", kategorie: 0 },
  50: { key: "TC_Geradheit_Messplatte_EN", einheit: "µm", übersetzung: " Geradheit der Messplatte im Bereich des EN", kategorie: 0 },
  51: { key: "TC_Positionsabweichung_Stuetzpunkte_EN", einheit: "mm", übersetzung: " Positionsabweichung der Stützpunkte des EN", kategorie: 0 },
  52: { key: "TC_Kalibrierung_Geradheit_EN", einheit: "µm", übersetzung: " Kalibrierung der Geradheit des EN", kategorie: 0 },
  53: { key: "TC_Laenge_stehender_Schenkel_MO", einheit: "mm", übersetzung: " Länge des stehenden Schenkels des MO", kategorie: 0 },
  54: { key: "TC_Stuetzpunktabstand_MO", einheit: "mm", übersetzung: " Stützpunktabstand des MO", kategorie: 0 },
  55: { key: "TC_Geradheit_Messplatte_MO", einheit: "µm", übersetzung: " Geradheit der Messplatte im Bereich des MO", kategorie: 0 },
  56: { key: "TC_Positionsabweichung_Stuetzpunkte_MO", einheit: "mm", übersetzung: " Positionsabweichung der Stützpunkte des MO", kategorie: 0 },
  57: { key: "TC_Kalibrierung_Geradheit_MO", einheit: "µm", übersetzung: " Kalibrierung der Geradheit des MO", kategorie: 0 },
  58: { key: "TC_Kalibrierung_Ebenheit_Messplatte", einheit: "µm", übersetzung: " Kalibrierung der Ebenheit der Messplatte", kategorie: 0 },
  59: { key: "TC_Positionsgenauigkeit_Stuetzpunkte", einheit: "mm", übersetzung: " Positionsgenauigkeit der Stützpunkte", kategorie: 0 },
  60: { key: "TC_Schrittweite_Geradheitskalibrierung_MO", einheit: "mm", übersetzung: " Schrittweite bei Geradheitskalibrierung des MO", kategorie: 0 },
  61: { key: "TC_Hoehendifferenz_Stuetzpunkte", einheit: "mm", übersetzung: " H÷hendifferenz der Stützpunkte", kategorie: 0 },
  62: { key: "TC_Laenge_Messobjekt", einheit: "mm", übersetzung: " Länge des Messobjekts", kategorie: 0 },
  63: { key: "TC_Anzahl_Verschiebungen_MO", einheit: "", übersetzung: " Anzahl der Verschiebungen des MO", kategorie: 0 },
  64: { key: "TC_Messbereichsendwert_Messeinrichtung", einheit: "mm", übersetzung: " Messbereichsendwert der Messeinrichtung", kategorie: 0 },
  65: { key: "TC_Hoehe_zu_Rechtwinkligkeit", einheit: "mm", übersetzung: " Zur Rechtwinkligkeit geh÷rende H÷he", kategorie: 0 },
  66: { key: "TC_Rh_Anzahl_Messwerte_pro_Teilmessstrecke", einheit: "", übersetzung: " Anzahl Messwerte pro Teilmessstrecke", kategorie: 0 },
  67: { key: "TC_Rh_Anzahl_Teilmessstrecken", einheit: "", übersetzung: " Anzahl  Teilmessstrecken", kategorie: 0 },
  68: { key: "TC_Rh_Ortabhaengige_Unsicherheit_in_y", einheit: "mm", übersetzung: " Ortsabhängige Unsicherheit in y-Richtung", kategorie: 0 },
  69: { key: "TC_Rh_Gradient_in_Rillenrichtung", einheit: "µm/mm", übersetzung: " Gradient in Rillenrichtung", kategorie: 0 },
  70: { key: "TC_Rh_Messpunktabstand", einheit: "µm", übersetzung: " Messpunktabstand", kategorie: 0 },
  71: { key: "TC_Rh_Tiefpasswellenlaengen", einheit: "µm", übersetzung: " Tiefpasswellenlängen", kategorie: 0 },
  72: { key: "TC_Rh_Kennwertaenderungsfaktor", einheit: "", übersetzung: " Tastspitzenabhängige Kennwertänderung", kategorie: 0 },
  73: { key: "TC_Rh_Gemessene_Kenngroesse", einheit: "µm", übersetzung: " Gemessener Kennwert", kategorie: 0 },
  74: { key: "TC_Rh_Anzahl_Wiederholungsmessungen_geaenderter_Antastort", einheit: "", übersetzung: " Anzahl Wiederholmessungen bei unterschiedlichen Antastorten", kategorie: 0 },
  75: { key: "TC_Rh_Anzahl_Wiederholmessungen_selber_Antastort", einheit: "", übersetzung: " Anzahl Wiederholmessungen am selben Antastort", kategorie: 0 },
  76: { key: "TC_Fm_Anzahl_Wiederholmessungen_StreuungAnzeige", einheit: "", übersetzung: " Anzahl Messungen (Streuung der Anzeige)", kategorie: 0 },
  77: { key: "TC_Fm_Abstand_zwischen_zwei_benachbarten_Profilpunkten", einheit: "µm", übersetzung: " Abstand zwischen zwei benachbarten Profilpunkten", kategorie: 0 },
  78: { key: "TC_Fm_Grenzwellenlaenge", einheit: "µm", übersetzung: " Grenzwellenlänge", kategorie: 0 },
  79: { key: "TC_Fm_Messwert_MO", einheit: "µm", übersetzung: " Richtiger Wert des Vergr÷ßerungsnormals", kategorie: 0 },
  80: { key: "TC_Fm_Richtiger_Wert_Rundheit_Kugelnormal", einheit: "µm", übersetzung: " Richtiger Wert der Rundheit des Kugelnormals", kategorie: 0 },
  81: { key: "TC_Fm_Messunsicherheit_der_Kalibrierung_Kugelnormal", einheit: "µm", übersetzung: " Messunsicherheit der Kalibrierung von Kugelnormal", kategorie: 0 },
  82: { key: "TC_Fm_Gemessenden_Exzentrizitaet", einheit: "mm", übersetzung: " Gemessenden Exzentrizität", kategorie: 0 },
  83: { key: "TC_Fm_Aussendurchmesser_MO", einheit: "mm", übersetzung: " Außendurchmesser des MO", kategorie: 0 },
  84: { key: "TC_Fm_Tastkugeldurchmesser", einheit: "mm", übersetzung: " Tastkugeldurchmesser", kategorie: 0 },
  85: { key: "TC_Fm_Innendurchmesser_MO", einheit: "mm", übersetzung: " Innendurchmesser des MO", kategorie: 0 },
  86: { key: "TC_Fm_Kippung_MO_XAchse", einheit: "µm/10mm", übersetzung: " Kippung des MO zu X-Achse", kategorie: 0 },
  87: { key: "TC_Fm_Kippung_MO_YAchse", einheit: "µm/10mm", übersetzung: " Kippung des MO zu Y-Achse", kategorie: 0 },
  88: { key: "TC_Fm_Radius_MO", einheit: "mm", übersetzung: "", kategorie: 0 },
  89: { key: "TC_Fm_Neigung_Zylinderachse_MO_zu_Flaeche_XOY", einheit: "Grad", übersetzung: " Neigung der Zylinderachse des MO zu Fläche XOY", kategorie: 0 },
  90: { key: "TC_Fm_Formabweichung_Normal", einheit: "µm", übersetzung: " Formabweichung des Normals", kategorie: 0 },
  91: { key: "TC_Fm_Kalibrierung_Normal", einheit: "µm", übersetzung: " Kalibrierung des Normals (Messunsicherheit)", kategorie: 0 },
  92: { key: "TC_Fm_Standardabweichung_Wiederholmessungen_Normal", einheit: "µm", übersetzung: " Standardabweichung der Wiederholmessungen des Normals", kategorie: 0 },
  93: { key: "TC_Fm_AnzahlMessungen_Fuehrungsabweichung", einheit: "", übersetzung: " Anzahl Messungen (Führungabweichung)", kategorie: 0 },
  94: { key: "TC_Fm_Gemessene_Rundheit_EN", einheit: "µm", übersetzung: " Gemessene Rundheit des Kugelnormals (EN)", kategorie: 0 },
  162: { key: "TC_Gewinde_Steigung", einheit: "mm", übersetzung: " Gewindesteigung", kategorie: 0 },
  95: { key: "TC_KTMG_Gemessener_Abstand", einheit: "mm", übersetzung: " Gemessener Abstand (< 100 mm)", kategorie: 0 },
  96: { key: "TC_KTMG_Konstanter_Anteil_EMPE", einheit: "µm", übersetzung: " Konstanter Anteil A des Grenzwerts E(MPE) der Längenmessabw.", kategorie: 0 },
  97: { key: "TC_KTMG_Anzahl_Messpunkte", einheit: "", übersetzung: " Anzahl der Messpunkte", kategorie: 0 },
  98: { key: "TC_KTMG_Gemessener_Winkel", einheit: "Grad", übersetzung: " Gemessener Winkel", kategorie: 0 },
  99: { key: "TC_KTMG_Laenge_kleinster_Schenkel", einheit: "mm", übersetzung: " Länge des kleinsten Schenkels (kleiner 100 mm)", kategorie: 0 },
  100: { key: "TC_KTMG_Gemessene_Geradheit", einheit: "µm", übersetzung: " Gemessene Geradheit", kategorie: 0 },
  101: { key: "TC_KTMG_Sektor_Kreis", einheit: "Grad", übersetzung: " Kreisabschnitt", kategorie: 0 },
  102: { key: "TC_3d_KMG_A", einheit: "", übersetzung: " Konstanter Teil A des Grenzwertes MPE(E) der Längenmessabw.", kategorie: 5 },
  103: { key: "TC_3d_KMG_K", einheit: "", übersetzung: " Faktor K des Grenzwertes der Längenmeßabw. MPE(E)=(A+L/K) µm", kategorie: 5 },
  141: { key: "TC_3d_KMG_LT", einheit: "mm", übersetzung: " Tasterlänge für spezifizierte Mehrfachtaster-Lageabweichung (LT)", kategorie: 5 },
  104: { key: "TC_3d_KMG_Uc", einheit: "µm", übersetzung: " Kalibrierunsicherheit des Kugelnormal-Durchmessers (µm) - U(C)", kategorie: 5 },
  105: { key: "TC_3d_KMG_alphaM", einheit: "10-6/K", übersetzung: " Ausdehnungskoeffizient der KMG-Maßstäbe (10-6/K) - Alpha M", kategorie: 5 },
  161: { key: "TC_3d_KMG_MpeML", einheit: "µm", übersetzung: " Grenzwert für Mehrtaster-Lageabweichung MPE(ML)", kategorie: 5 },
  106: { key: "TC_3d_KMG_Tm", einheit: "°C", übersetzung: " Mittlere Temperatur der KMG-Maßstäbe (°C) - tM", kategorie: 4 },
  107: { key: "TC_3d_KMG_deltaTm", einheit: "K", übersetzung: " Max. Abweichung von der mittleren Temperatur (K) - Maßstab", kategorie: 4 },
  108: { key: "TC_3d_KMG_alphaW", einheit: "10-6/K", übersetzung: " Ausdehnungskoeffizient des Werkstücks (10-6/K)", kategorie: 4 },
  109: { key: "TC_3d_KMG_Tw", einheit: "°C", übersetzung: " Mittlere Temperatur des Werkstücks (°C)", kategorie: 4 },
  110: { key: "TC_3d_KMG_deltaTw", einheit: "K", übersetzung: " Max. Abweichung von der mittleren Temperatur (K) - Werkstück", kategorie: 4 },
  111: { key: "TC_3d_DUME_D", einheit: "mm", übersetzung: " Nennmaß des Durchmessers (D)", kategorie: 1 },
  112: { key: "TC_3d_DUME_alpha", einheit: "°", übersetzung: " Winkelbereich der Meßpunkte am Umfang (Standard 360°)", kategorie: 1 },
  113: { key: "TC_3d_DUME_l", einheit: "mm", übersetzung: " Zylinder: Länge des Formelements (Gesamtlänge bis Rand)", kategorie: 1 },
  142: { key: "TC_3d_DUME_LM", einheit: "mm", übersetzung: " Kegel: Messlänge (Bereich der Messpunkte)", kategorie: 1 },
  114: { key: "TC_3d_FORM_L", einheit: "mm", übersetzung: " Nennmaß der Länge (gr÷ßere Länge) (L)", kategorie: 1 },
  115: { key: "TC_3d_FORM_DL", einheit: "mm", übersetzung: " Nennmaß der Breite (kleinere Länge) (l)", kategorie: 1 },
  116: { key: "TC_3d_FORM_F", einheit: "µm", übersetzung: " Formabweichung am Normal aufgrund der Tasterbiegung (µm)", kategorie: 3 },
  164: { key: "TC_3d_FORM_FN", einheit: "µm", übersetzung: " Formabweichung (Rundheit) am Normal aus Zertifikat F(N)", kategorie: 2 },
  165: { key: "TC_3d_FORM_FKMG", einheit: "µm", übersetzung: " Formabweichung (Rundheit) am Normal aus Messung F(KMG)", kategorie: 2 },
  117: { key: "TC_3d_ABST_L", einheit: "mm", übersetzung: " Nennmaß des Abstandes (bei Position theoretischens Maß)", kategorie: 1 },
  118: { key: "TC_3d_ABST_LM1", einheit: "mm", übersetzung: " Messlänge am tolerierten Element (Bereich der Messpunkte) - L(ME)", kategorie: 1 },
  119: { key: "TC_3d_ABST_LE1", einheit: "mm", übersetzung: " Abstand des Schwerpunktes von der Nullebene -  L(SE)", kategorie: 1 },
  120: { key: "TC_3d_ABST_LM2", einheit: "mm", übersetzung: " Messlänge am Bezugselement (Bereich der Messpunkte) - L(MB)", kategorie: 1 },
  121: { key: "TC_3d_ABST_LE2", einheit: "mm", übersetzung: " Abstand des Schwerpunktes von der Nullebene - L(SB)", kategorie: 1 },
  144: { key: "TC_3D_ABST_LTE", einheit: "mm", übersetzung: " Tasterlänge E  L(TE)", kategorie: 3 },
  145: { key: "TC_3D_ABST_LTB", einheit: "mm", übersetzung: " Tasterlänge B  L(TB)", kategorie: 3 },
  122: { key: "TC_3d_Ri_LA", einheit: "mm", übersetzung: " Kleinster Abstand des tolerierten Elements vom Bezugselement - L(A)", kategorie: 1 },
  123: { key: "TC_3d_Ri_Alpha", einheit: "°", übersetzung: " Nennwert des Winkels (in Grad) - Alpha", kategorie: 1 },
  124: { key: "TC_3d_Ri_LME", einheit: "mm", übersetzung: " Messlänge am tolerierten Element (Bereich der Messpunkte)- L(ME)", kategorie: 1 },
  125: { key: "TC_3d_Ri_LE", einheit: "mm", übersetzung: " Auswertelänge (Länge des tolerierten Elements) - L(E)", kategorie: 1 },
  126: { key: "TC_3d_Ri_LMB", einheit: "mm", übersetzung: " Messlänge am Bezugselements (Bereich der Messpunkte) - L(MB)", kategorie: 1 },
  146: { key: "TC_3d_Ri_LTE1", einheit: "mm", übersetzung: " Tasterlänge 1 L(TE1)", kategorie: 3 },
  147: { key: "TC_3d_Ri_LTE2", einheit: "mm", übersetzung: " Tasterlänge 2 L(TE2)", kategorie: 3 },
  148: { key: "TC_3d_Ri_LTB1", einheit: "mm", übersetzung: "", kategorie: 0 },
  149: { key: "TC_3d_Ri_LTB2", einheit: "mm", übersetzung: "", kategorie: 0 },
  127: { key: "TC_3d_Sym_DE", einheit: "mm", übersetzung: " Breite bzw. Durchmesser des tolerierten Elements - D(E)", kategorie: 1 },
  128: { key: "TC_3d_Sym_LE", einheit: "mm", übersetzung: " Länge des tolerierten Elements - L(E)", kategorie: 1 },
  150: { key: "TC_3d_Sym_LME", einheit: "mm", übersetzung: " Messlänge am tolerierten Element (Bereich der Messpunkte) - L(ME)", kategorie: 1 },
  129: { key: "TC_3d_Sym_DB", einheit: "mm", übersetzung: " Breite bzw. Durchmesser des Bezugselements - D(B)", kategorie: 1 },
  151: { key: "TC_3d_Sym_LB", einheit: "mm", übersetzung: " Länge des Bezugselements (Länge bis zum Rand) - L(B)", kategorie: 1 },
  130: { key: "TC_3d_Sym_LMB", einheit: "mm", übersetzung: " Messlänge des Bezugselements (Bereich der Messpunkte) - L(MB)", kategorie: 1 },
  152: { key: "TC_3d_Sym_LTE", einheit: "mm", übersetzung: " Tasterlänge E L(TE)", kategorie: 3 },
  153: { key: "TC_3d_Sym_LTB", einheit: "mm", übersetzung: " Tasterlänge B L(TB)", kategorie: 3 },
  131: { key: "TC_3d_Koax_DE", einheit: "mm", übersetzung: " Durchmesser des tolerierten Elements - D(E)", kategorie: 1 },
  132: { key: "TC_3d_Koax_LE", einheit: "mm", übersetzung: " Länge des tolerierten Elements - L(E)", kategorie: 1 },
  133: { key: "TC_3d_Koax_LA", einheit: "mm", übersetzung: " Gr÷ßter Abstand des tol. Elements zur Mitte des Bezugselements-L(A)", kategorie: 1 },
  134: { key: "TC_3d_Koax_DB", einheit: "mm", übersetzung: " Gr÷ßter Durchmesser des Bezugselements - D(B)", kategorie: 1 },
  135: { key: "TC_3d_Koax_LB", einheit: "mm", übersetzung: " Länge des Bezugselements (Gesamtlänge bis zum Rand) -  L(B)", kategorie: 1 },
  136: { key: "TC_3d_Koax_LMB", einheit: "mm", übersetzung: " Messlänge am Bezugselement (Bereich der Messpunkte) - L(MB)", kategorie: 1 },
  154: { key: "TC_3d_Koax_LME", einheit: "mm", übersetzung: " Messlänge am tolerierten Element (Bereich der Messpunkte) - L(ME)", kategorie: 1 },
  155: { key: "TC_3d_Koax_LT_entfaellt", einheit: "mm", übersetzung: " -", kategorie: 0 },
  156: { key: "TC_3d_Koax_LTB", einheit: "mm", übersetzung: " Tasterlänge B- L(TB)", kategorie: 3 },
  157: { key: "TC_3d_Koax_LTE", einheit: "mm", übersetzung: " Tasterlänge E- L(TE)", kategorie: 3 },
  137: { key: "TC_3d_KoaxGA_DE", einheit: "mm", übersetzung: " Durchmesser des tolerierten Elements - D(E)", kategorie: 1 },
  138: { key: "TC_3d_KoaxGA_LME", einheit: "mm", übersetzung: " Messlänge am tolerierten Element (Bereich der Messpunkte) L(ME)", kategorie: 1 },
  139: { key: "TC_3d_KoaxGA_LE", einheit: "mm", übersetzung: " Auswertelänge am tolerierten Element (Länge bis zum Rand) - L(E)", kategorie: 1 },
  140: { key: "TC_3d_KoaxGA_LB", einheit: "mm", übersetzung: " Bezugslänge (Mittenabstand der beiden Bezugselemente) - L(E)", kategorie: 1 },
  158: { key: "TC_3d_KoaxGA_LA", einheit: "mm", übersetzung: "!!! siehe oben  TC_3d_Koax_LA		Gr÷ßter Abstand des tol. Elements zur Mitte des Bezugselements-L(A)", kategorie: 1 },
  159: { key: "TC_3d_KoaxGA_LTB", einheit: "mm", übersetzung: "!!!=  TC_3d_Koax_LTB		Tasterlänge B- L(TB)", kategorie: 3 },
  160: { key: "TC_3d_KoaxGA_LTE", einheit: "mm", übersetzung: "!!!= TC_3d_Koax_LTE		Tasterlänge E- L(TE)", kategorie: 3 },
  163: { key: "TC_3D_NennLaenge_LD", einheit: "mm", übersetzung: "	Nennmaß der Länge bzw. Durchmessers L(D)", kategorie: 1 },
  166: { key: "TC_3d_KMG_AUFLOES", einheit: "°", übersetzung: "", kategorie: 0 },
  167: { key: "TC_3d_PktPkt_dist", einheit: "mm", übersetzung: "Abstand toleriertem zu Bezugselement", kategorie: 0 },
  168: { key: "TC_3d_PktPkt_Wechsel", einheit: "ja/nein", übersetzung: "Tasterwechsel", kategorie: 3 },
  169: { key: "TC_3d_PktPkt_nTastBe", einheit: "", übersetzung: "Anzahl Antastungen Bezugselement", kategorie: 2 },
  170: { key: "TC_3d_PktPkt_nTastTe", einheit: "", übersetzung: "Anzahl Antastungen toleriertes Element", kategorie: 2 },
  171: { key: "TC_3d_PktPkt_SigBe", einheit: "mm", übersetzung: "Standardabweichung bei Antastung des BE", kategorie: 2 },
  172: { key: "TC_3d_PktPkt_SigTe", einheit: "mm", übersetzung: "Standardabweichung bei Antastung des TE", kategorie: 2 },
  173: { key: "TC_3d_PktPkt_ScanKgl", einheit: "Grad", übersetzung: "Bereich zum Scannen von Kugeln", kategorie: 1 },
  174: { key: "TC_3d_PktPkt_MBe", einheit: "W/L", übersetzung: "Maximale Harmonik des Profils des BE . Apriori", kategorie: 0 },
  175: { key: "TC_3d_PktPkt_Mte", einheit: "W/L", übersetzung: "Maximale Harmonik des Profils des BE . Apriori", kategorie: 0 },
  176: { key: "TC_3d_PktPkt_Temp", einheit: "°C", übersetzung: "Raumtemperatur", kategorie: 4 },
  177: { key: "TC_3d_PktPkt_Gamma0", einheit: "mm", übersetzung: "Koeff fόr ZufAbw aufgrund Winkel de Sektor", kategorie: 0 },
  178: { key: "TC_3d_PktPkt_Gamma1", einheit: "Grad", übersetzung: "Koeff fόr ZufAbw aufgrund Winkel de Sektor", kategorie: 0 },
  179: { key: "TC_3d_PktPkt_WinkelSeg_BE", einheit: "Grad", übersetzung: "Winkel Antastbereich (Segment) BE", kategorie: 1 },
  180: { key: "TC_3d_PktPkt_WinkelSeg_TE", einheit: "Grad", übersetzung: "Winkel Antastbereich (Segment) tolerirtes Element", kategorie: 1 },
  181: { key: "TC_3d_PktPkt_AnzSims", einheit: "", übersetzung: "Anzahl Simulationen pro Messpunkt", kategorie: 0 },
  182: { key: "TC_3d_PktPkt_Dia_BE", einheit: "mm", übersetzung: "Durchmesser Kreis 1 BE", kategorie: 1 },
  183: { key: "TC_3d_PktPkt_Dia_TE", einheit: "mm", übersetzung: "Durchmesser Kreis 2 BE", kategorie: 1 },
  184: { key: "TC_3d_KMG_AmpX", einheit: "mm", übersetzung: "Amplidude Streuung X", kategorie: 0 },
  185: { key: "TC_3d_KMG_AmpY", einheit: "mm", übersetzung: "Amplidude Streuung Y", kategorie: 0 },
};
