import app.services.component_service.DreiDComponents as d
import app.services.component_service.components as k
from app.services.component_service.EverythinForComponents.TMU_ConstList import (
    TMU_ConstList,
)


class ComponentFactory:
    COMPONENTS = {
        1001: k.TK_KalibrierungME,
        1002: k.TK_ErmittelteMessabweichungME,
        1003: k.TK_AufloesungME,
        1005: k.TK_Ebenheit_1_2_ME,
        1006: k.TK_Ebenheit_1_2_MO,
        1007: k.TK_ParallelitaetMessflaechenME,
        1008: k.TK_KorrParallelitaet_MO,
        1009: k.TK_TempDifferenz_MO_ME,
        1010: k.TK_AbweichungMittlereTemp_MO_ME,
        1011: k.TK_VerformungMO,
        1012: k.TK_Korr_Biegung_ME,
        1013: k.TK_RundheitMessflaeche_1_2_MO,
        1014: k.TK_Zylindrizitaet_MO_1_2,
        1015: k.TK_Korr_Zylin_ME_1_2,
        1016: k.TK_Korr_Zylin_GN_1_2,
        1017: k.TK_Korr_Rundheit_ME_1_2,
        1018: k.TK_Korr_Rundheit_EN_1_2,
        1019: k.TK_Korr_Rundheit_GN_1_2,
        1020: k.TK_Korr_Ebenheit_1_2,
        1021: k.TK_Korr_Parallelitaet_EN,
        1022: k.TK_Verformung_MOsph_MEplan,
        1023: k.TK_Verformung_MOsph_MEsph,
        1024: k.TK_Verformung_MOzyl_MEsph,
        1025: k.TK_Aufloesung_ME_Einstell,
        1026: k.TK_Abweichung_Nennmass_EN,
        1027: k.TK_Kalibrierung_EN,
        1028: k.TK_Korr_TempDifferenz_EN_ME,
        1029: k.TK_Korr_TempDifferenz_EN_ME_20,
        1031: k.TK_Drift_GN,
        1032: k.TK_Korr_Abplattung_Messkraft,
        10321: k.TK_Korr_Abplattung_Messkraft_ME_MO,
        10322: k.TK_Korr_Abplattung_Messkraft_ME_GN,
        1033: k.TK_Kalibrierung_Faktor_Kennlinie_ME,
        1034: k.TK_Kalibrierung_Parm_Kennlinie_ME,
        1035: k.TK_Nichtlinearitaet_Kennlinie_ME,
        1036: k.TK_Zeitdrift_ME,
        1037: k.TK_Verformung_Differenz_MO_GN,
        1038: k.TK_AufloesungMO,
        1039: k.TK_AnstellwinkelHebel,
        1040: k.TK_Wiederholpraezision,
        1041: k.TK_NichtZentrischeAntastung,
        1042: k.TK_StreuungMesskraft,
        1043: k.TK_AbweichungPoissonKoeffizientMO_EN,
        1044: k.TK_AbweichungElastizitaetsModul_MO_EN,
        1045: k.TK_Messkraft_3Draht_Methode,
        1046: k.TK_KalibrierungMessdraehte,
        1047: k.TK_Zylindrizitaet_Messdraehte,
        1048: k.TK_GewindeProfilwinkel,
        1049: k.TK_Messkraft_2Kugel_Methode,
        1050: k.TK_KalibrierungMesskugeln,
        1051: k.TK_RundheitMesskugeln,
        1052: k.TK_Geradheit_stehender_Schenkel_EN,
        1053: k.TK_Geradheit_stehender_Schenkel_MO,
        1054: k.TK_Geradheit_liegender_Schenkel_EN,
        1055: k.TK_Geradheit_liegender_Schenkel_MO,
        1056: k.TK_Neigung_Winkelnormal_EN,
        1057: k.TK_Neigung_Messobjekts_MO,
        1059: k.TK_Kalibrierung_Geradheit_stehender_Schenkel_EN,
        1060: k.TK_Kalibrierung_Geradheit_stehender_Schenkel_MO,
        1061: k.TK_Kalibrierung_Geradheit_Hoehenmessgeraets,
        1062: k.TK_Geradheitabweichung_Hoehenmessgeraets,
        1063: k.TK_Positioniergenauigkeit_Taster_X_Achse,
        1064: k.TK_Ebenheit_Messplatte,
        1065: k.TK_Kalibrierung_Ebenheit_Messplatte,
        1066: k.TK_Geradheit_Schenkelinnenseite,
        1067: k.TK_Kalibrierung_Geradheit_Schenkelinnenseite,
        1071: k.TK_Strichbreite_EN,
        1072: k.TK_Strichbreite_MO,
        1073: k.TK_Strichbreite_ME,
        1074: k.TK_Winkel_Achsen_MO_ME,
        1075: k.TK_Anzahl_Verschiebungen_MO,
        1076: k.TK_Kalibrierung_Rechwinkligkeit,
        1077: k.TK_Ermittelte_Rechwinkligkeit,
        1078: k.TK_Rh_Kalibrierung_Einstellnormal_EN,
        1079: k.TK_Rh_Drift_Richtiger_Wert_vom_EN,
        1080: k.TK_Rh_Unterschied_Kalibrierort_EN,
        1081: k.TK_Rh_Wiederholpraezision_Antastung_MO,
        1082: k.TK_Rh_Topografie_MO,
        1083: k.TK_Rh_Fuehrungsabweichung,
        1084: k.TK_Rh_Drift_Fuehrungsabweichung,
        1085: k.TK_Rh_Grundrauschen,
        1086: k.TK_Rh_Drift_Grundrauschen,
        1087: k.TK_Rh_Verformung_MO,
        1088: k.TK_Rh_Abweichung_Tastspitzenradius_vom_Nennwert,
        1089: k.TK_Rh_Messunsicherheit_Kalibrierung_Tastspitzenradius,
        1090: k.TK_Rh_Unbekannte_systematische_Abweichung,
        1091: k.TK_Rh_Kalibrierung_Einstellnormal_EN_TG,
        1092: k.TK_Rh_Drift_Richtiger_Wert_von_EN_TG,
        1093: k.TK_Rh_Kalibrierort_Kalibrierung_EN_TG,
        1094: k.TK_Rh_Wiederholpraezision_Antastung_TG,
        1095: k.TK_Rh_Fuehrungsabweichung_TG,
        1096: k.TK_Rh_Grundrauschen_TG,
        1097: k.TK_Rh_Verformung_EN_TG,
        1098: k.TK_Rh_Abweichung_Tastspitzenradius_Nennwert,
        1099: k.TK_Rh_Messunsicherheit_Kalibrierung_Tastspitzenradius_TG,
        1100: k.TK_Fm_Streuung_Anzeige_ME_in_jedem_Profilpunkt,
        1101: k.TK_Fm_Homogenitaet_MO,
        1102: k.TK_Fm_Reinigung_MO,
        1103: k.TK_Fm_Dynamische_Eingenschaften_ME,
        1104: k.TK_Fm_Rauschen_ME,
        1105: k.TK_Fm_Streuung_Empfindlichkeit_ME,
        1106: k.TK_Fm_Unsicherheit_Vergroesserungsnormal,
        1107: k.TK_Fm_Streuung_Spindel_ME,
        1108: k.TK_Fm_Linearitaet_ME,
        1109: k.TK_Fm_Hysterese_ME,
        1110: k.TK_Fm_Exzentrizitaet_MO_Aus,
        1111: k.TK_Fm_Exzentrizitaet_MO_Inn,
        1112: k.TK_Fm_Nivellierung_Zylinderachse_MO_Rund,
        1113: k.TK_Fm_Nivellierung_Zylinderachse_MO_Gerade,
        1114: k.TK_Fm_Deformation_MO,
        1115: k.TK_Fm_Fuehrungsabweichung_ME,
        1116: k.TK_Fm_Temperatur,
        1117: k.TK_Fm_Drift_Empfindlichkeit_ME,
        1118: k.TK_Fm_Messabweichung_Kalibrierung_ME_Tastsystem,
        1119: k.TK_Fm_Kalibrierung_ME_Tastsystem,
        1121: k.TK_KTMG_Abstand_system,
        1122: k.TK_KTMG_Abstand_zufall,
        1123: k.TK_KTMG_Winkel_system,
        1124: k.TK_KTMG_Winkel_zufall,
        1125: k.TK_KTMG_Winkel_plastVerform,
        1126: k.TK_KTMG_Geradheit_system,
        1127: k.TK_KTMG_Geradheit_zufall,
        1128: k.TK_KTMG_Radius_system,
        1129: k.TK_KTMG_Radius_zufall,
        1130: k.TK_KTMG_Winkel_Tastspitzenradius,
        1301: d.TK_3d_Dw,
        1320: d.TK_3dA_DeltaDT,
        1303: d.TK_3d_DeltaDC,
        1304: d.TK_3d_DeltaLkmg,
        1323: d.TK_3dA_LalphaM,
        1324: d.TK_3dA_LalphaW,
        1325: d.TK_3dA_LtM,
        1326: d.TK_3dA_LtW,
        1377: d.TK_3d_Delta_L_t,
        1378: d.TK_3d_ResKMG,
        1379: d.TK_3d_Wi_WE,
        1380: d.TK_3d_Wi_WB,
        1381: d.TK_3d_Wi_DeltaEKMG,
        1312: d.TK_3dA_X1,
        1313: d.TK_3dA_W1,
        1314: d.TK_3dA_DeltaXT1,
        1315: d.TK_3dA_DeltaRT1,
        1316: d.TK_3dA_X2,
        1317: d.TK_3dA_W2,
        1318: d.TK_3dA_DeltaXT2,
        1319: d.TK_3dA_DeltaRT2,
        1321: d.TK_3dA_DeltaDC,
        1322: d.TK_3dA_DeltaLKMG,
        1368: d.TK_3dA_DeltaXTR,


    }

    @staticmethod
    def get_component(modell: "TMU_Modell", type_name: str, lfdnr: int):
        component_class = ComponentFactory.COMPONENTS.get(type_name)
        return component_class(modell, TMU_ConstList, lfdnr) if component_class else None

    @staticmethod
    def get_all_components():
        return [
            component_class(None, TMU_ConstList, 0)
            for component_class in ComponentFactory.COMPONENTS.values()
        ]
