"""rollenverteilung

Revision ID: 0c96451899d5
Revises: ccf78c7298cd
Create Date: 2026-08-25 14:23:01.081335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c96451899d5'
down_revision: Union[str, None] = 'ccf78c7298cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kmgs', sa.Column('fk_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kmgs', 'users', ['fk_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kmgs', type_='foreignkey')
    op.drop_column('kmgs', 'fk_user_id')
    # ### end Alembic commands ###
