"""anzahl messungen hinzugefü

Revision ID: 16d1b83ba24c
Revises: a13c884f7b9e
Create Date: 2025-05-09 11:54:42.627797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d1b83ba24c'
down_revision: Union[str, None] = 'a13c884f7b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod_components', sa.Column('messpunkt_anzahl', sa.Integer(), nullable=True))
    op.add_column('mod_components', sa.Column('anzahl_messungen', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mod_components', 'anzahl_messungen')
    op.drop_column('mod_components', 'messpunkt_anzahl')
    # ### end Alembic commands ###
