"""Modcreation und modmod  hinzugefügt

Revision ID: 17300be03e0a
Revises: 078aa04a0223
Create Date: 2025-05-07 08:31:21.773074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17300be03e0a'
down_revision: Union[str, None] = '078aa04a0223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modells', sa.Column('modcreation', sa.DATETIME(), nullable=True))
    op.add_column('modells', sa.Column('modmod', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modells', 'modmod')
    op.drop_column('modells', 'modcreation')
    # ### end Alembic commands ###
