"""add old import id und fk_user zu kmg

Revision ID: 1fac8aaa8fbb
Revises: a37133a5538b
Create Date: 2026-08-26 17:35:53.515920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fac8aaa8fbb'
down_revision: Union[str, None] = 'a37133a5538b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kmgs', sa.Column('fk_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kmgs', 'users', ['fk_user_id'], ['id'])
    op.add_column('modells', sa.Column('old_import_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modells', 'old_import_id')
    op.drop_constraint(None, 'kmgs', type_='foreignkey')
    op.drop_column('kmgs', 'fk_user_id')
    # ### end Alembic commands ###
