"""gegenstanf zu gegenstand

Revision ID: 20babbe2d97c
Revises: ea8f9669f3ac
Create Date: 2025-05-08 11:42:47.649509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20babbe2d97c'
down_revision: Union[str, None] = 'ea8f9669f3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modells', sa.Column('gegenstand', sa.Integer(), nullable=True))
    op.drop_column('modells', 'gegenstanf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modells', sa.Column('gegenstanf', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('modells', 'gegenstand')
    # ### end Alembic commands ###
