"""modell um 3d attribute erweitert

Revision ID: 26b3f07ecb4a
Revises: 2e498fdfc917
Create Date: 2025-06-25 12:27:20.358639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b3f07ecb4a'
down_revision: Union[str, None] = '2e498fdfc917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modells', sa.Column('taster', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('merkmal', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('element', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('punktmusterB1', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('tasterschaft1', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('tasterschaft2', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('punktmusterR1', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('punktmusterR2', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('taster1', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('taster2', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('abstand', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modells', 'abstand')
    op.drop_column('modells', 'taster2')
    op.drop_column('modells', 'taster1')
    op.drop_column('modells', 'punktmusterR2')
    op.drop_column('modells', 'punktmusterR1')
    op.drop_column('modells', 'tasterschaft2')
    op.drop_column('modells', 'tasterschaft1')
    op.drop_column('modells', 'punktmusterB1')
    op.drop_column('modells', 'element')
    op.drop_column('modells', 'merkmal')
    op.drop_column('modells', 'taster')
    # ### end Alembic commands ###
