"""messpunkt anzahl default value gleich 0

Revision ID: 272fd1dd3a6c
Revises: ea12c649a244
Create Date: 2025-08-28 10:11:09.602482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272fd1dd3a6c'
down_revision: Union[str, None] = 'ea12c649a244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
