"""ForeignKey Anakonst to Anamu

Revision ID: 28fc7ad06629
Revises: 315f502e612b
Create Date: 2025-04-29 10:46:48.754984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fc7ad06629'
down_revision: Union[str, None] = '315f502e612b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'anakonst', 'ana_mu', ['fk_anamu'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anakonst', type_='foreignkey')
    # ### end Alembic commands ###
