"""berechnen zu anakomp

Revision ID: 2e498fdfc917
Revises: 30eabcfbb0bf
Create Date: 2025-06-24 13:31:53.005434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e498fdfc917'
down_revision: Union[str, None] = '30eabcfbb0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anakomp', sa.Column('berechnen', sa.Integer(), nullable=True))
    op.alter_column('anakonst', 'constval',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anakonst', 'constval',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.drop_column('anakomp', 'berechnen')
    # ### end Alembic commands ###
