"""fk_user_id zu anakonst

Revision ID: 30eabcfbb0bf
Revises: 5c1f5813f0c7
Create Date: 2025-05-22 12:35:27.030945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30eabcfbb0bf'
down_revision: Union[str, None] = '5c1f5813f0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anakonst', sa.Column('fk_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'anakonst', 'users', ['fk_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anakonst', type_='foreignkey')
    op.drop_column('anakonst', 'fk_user_id')
    # ### end Alembic commands ###
