"""ForeignKey in anamu for kmgs

Revision ID: 315f502e612b
Revises:
Create Date: 2025-04-24 10:38:33.570786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "315f502e612b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ana_mu", sa.Column("fk_kmg", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "ana_mu", "kmgs", ["fk_kmg"], ["id"])
    op.drop_column("ana_mu", "kmg_ident")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ana_mu", sa.Column("kmg_ident", mysql.VARCHAR(length=255), nullable=True)
    )
    op.drop_constraint(None, "ana_mu", type_="foreignkey")
    op.drop_column("ana_mu", "fk_kmg")
    # ### end Alembic commands ###
