"""anzahl messungen hinzugefügt

Revision ID: 3722d51e8c9f
Revises: 6247c01cb69a
Create Date: 2025-05-09 11:23:53.500148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3722d51e8c9f'
down_revision: Union[str, None] = '6247c01cb69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anakomp', sa.Column('anzahl_messungen', sa.Integer(), nullable=True))
    op.add_column('mod_components', sa.Column('messpunkt_anzahl', sa.Integer(), nullable=True))
    op.add_column('mod_components', sa.Column('anzahl_messungen', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mod_components', 'anzahl_messungen')
    op.drop_column('mod_components', 'messpunkt_anzahl')
    op.drop_column('anakomp', 'anzahl_messungen')
    # ### end Alembic commands ###
