"""ForeignKey Anamu to User

Revision ID: 3ca455caad67
Revises: b09463fe30c2
Create Date: 2025-04-29 11:21:26.658738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3ca455caad67'
down_revision: Union[str, None] = 'b09463fe30c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ana_mu', sa.Column('fk_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ana_mu', 'users', ['fk_user'], ['id'])
    op.drop_column('ana_mu', 'user')
    op.drop_constraint('anakonst_ibfk_2', 'anakonst', type_='foreignkey')
    op.drop_column('anakonst', 'fk_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anakonst', sa.Column('fk_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('anakonst_ibfk_2', 'anakonst', 'users', ['fk_user'], ['id'])
    op.add_column('ana_mu', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ana_mu', type_='foreignkey')
    op.drop_column('ana_mu', 'fk_user')
    # ### end Alembic commands ###
