"""add old_import_id to modells

Revision ID: 519974164cdd
Revises: cad9699e5958
Create Date: 2026-08-24 15:53:39.818662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519974164cdd'
down_revision: Union[str, None] = 'cad9699e5958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modells', sa.Column('old_import_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modells', 'old_import_id')
    # ### end Alembic commands ###
