"""anzahl messungen hinzugefügt

Revision ID: 53b1899913c2
Revises: 4b3182bcdc1d
Create Date: 2025-05-09 11:30:44.274398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b1899913c2'
down_revision: Union[str, None] = '4b3182bcdc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod_components', sa.Column('messpunkt_anzahl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mod_components', 'messpunkt_anzahl')
    # ### end Alembic commands ###
