"""fk_user_id zu anakomp

Revision ID: 5c1f5813f0c7
Revises: f410b4138ddb
Create Date: 2025-05-21 13:08:20.446422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1f5813f0c7'
down_revision: Union[str, None] = 'f410b4138ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anakomp', sa.Column('fk_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'anakomp', 'users', ['fk_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anakomp', type_='foreignkey')
    op.drop_column('anakomp', 'fk_user_id')
    # ### end Alembic commands ###
