"""art des maßes hinzugefügt

Revision ID: 5ddd7609559d
Revises: 272fd1dd3a6c
Create Date: 2025-08-28 15:58:32.083730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddd7609559d'
down_revision: Union[str, None] = '272fd1dd3a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modells', sa.Column('artdesmasses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modells', 'artdesmasses')
    # ### end Alembic commands ###
