"""Modell geändert, neue felder für so paar winkel sachen und punktmuster etc

Revision ID: 6c1a54116f5b
Revises: 17300be03e0a
Create Date: 2025-05-07 16:06:43.900114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1a54116f5b'
down_revision: Union[str, None] = '17300be03e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modells', sa.Column('punktmuster', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('Element1', sa.String(length=255), nullable=True))
    op.add_column('modells', sa.Column('Element2', sa.String(length=255), nullable=True))
    op.add_column('modells', sa.Column('Bezug1', sa.String(length=255), nullable=True))
    op.add_column('modells', sa.Column('Bezug2', sa.String(length=255), nullable=True))
    op.add_column('modells', sa.Column('winkelE1', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('winkelE2', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('winkelB1', sa.Integer(), nullable=True))
    op.add_column('modells', sa.Column('winkelB2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modells', 'winkelB2')
    op.drop_column('modells', 'winkelB1')
    op.drop_column('modells', 'winkelE2')
    op.drop_column('modells', 'winkelE1')
    op.drop_column('modells', 'Bezug2')
    op.drop_column('modells', 'Bezug1')
    op.drop_column('modells', 'Element2')
    op.drop_column('modells', 'Element1')
    op.drop_column('modells', 'punktmuster')
    # ### end Alembic commands ###
