"""anzahl messungen hinzugefüg

Revision ID: a13c884f7b9e
Revises: 53b1899913c2
Create Date: 2025-05-09 11:53:31.936132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13c884f7b9e'
down_revision: Union[str, None] = '53b1899913c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anakomp', sa.Column('messpunkt_anzahl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anakomp', 'messpunkt_anzahl')
    # ### end Alembic commands ###
