"""add fk_company to all tables

Revision ID: a37133a5538b
Revises: cad9699e5958
Create Date: 2026-08-26 17:32:25.057426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a37133a5538b'
down_revision: Union[str, None] = 'cad9699e5958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ana_mu', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ana_mu', 'companies', ['fk_company'], ['id'])
    op.add_column('anakomp', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'anakomp', 'companies', ['fk_company'], ['id'])
    op.drop_column('kmgs', 'fk_user_id')
    op.add_column('mod_components', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mod_components', 'companies', ['fk_company'], ['id'])
    op.add_column('modells', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modells', 'companies', ['fk_company'], ['id'])
    op.drop_column('modells', 'old_import_id')
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)
    op.add_column('modells', sa.Column('old_import_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'modells', type_='foreignkey')
    op.drop_column('modells', 'fk_company')
    op.drop_constraint(None, 'mod_components', type_='foreignkey')
    op.drop_column('mod_components', 'fk_company')
    op.add_column('kmgs', sa.Column('fk_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'anakomp', type_='foreignkey')
    op.drop_column('anakomp', 'fk_company')
    op.drop_constraint(None, 'ana_mu', type_='foreignkey')
    op.drop_column('ana_mu', 'fk_company')
    # ### end Alembic commands ###
