"""ForeignKey Anamu to User

Revision ID: b09463fe30c2
Revises: 28fc7ad06629
Create Date: 2025-04-29 11:05:18.056631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09463fe30c2'
down_revision: Union[str, None] = '28fc7ad06629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anakonst', sa.Column('fk_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'anakonst', 'users', ['fk_user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anakonst', type_='foreignkey')
    op.drop_column('anakonst', 'fk_user')
    # ### end Alembic commands ###
