"""Fix foreign key relationship

Revision ID: be0821a5f69b
Revises: 543b3966fe64
Create Date: 2025-05-06 10:23:27.257212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be0821a5f69b'
down_revision: Union[str, None] = '543b3966fe64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['fk_company'], ['id'])
    op.drop_column('users', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'companies', ['company_id'], ['id'])
    op.drop_column('users', 'fk_company')
    # ### end Alembic commands ###
