"""add modell_texts table

Revision ID: cad9699e5958
Revises: 8f727a1a758b
Create Date: 2026-06-25 12:02:19.800286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad9699e5958'
down_revision: Union[str, None] = '8f727a1a758b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modell_texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deutsch', sa.String(length=500), nullable=True),
    sa.Column('englisch', sa.String(length=500), nullable=True),
    sa.Column('spanisch', sa.String(length=500), nullable=True),
    sa.Column('french', sa.String(length=500), nullable=True),
    sa.Column('italian', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modell_texts')
    # ### end Alembic commands ###
