"""add fk_company to all tables

Revision ID: ccf78c7298cd
Revises: 3db29298546e
Create Date: 2026-08-25 13:56:26.371679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf78c7298cd'
down_revision: Union[str, None] = '3db29298546e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ana_mu', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ana_mu', 'companies', ['fk_company'], ['id'])
    op.add_column('anakomp', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'anakomp', 'companies', ['fk_company'], ['id'])
    op.add_column('anakonst', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'anakonst', 'companies', ['fk_company'], ['id'])
    op.add_column('kmgs', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kmgs', 'companies', ['fk_company'], ['id'])
    op.add_column('mod_components', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mod_components', 'companies', ['fk_company'], ['id'])
    op.add_column('modells', sa.Column('fk_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modells', 'companies', ['fk_company'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modells', type_='foreignkey')
    op.drop_column('modells', 'fk_company')
    op.drop_constraint(None, 'mod_components', type_='foreignkey')
    op.drop_column('mod_components', 'fk_company')
    op.drop_constraint(None, 'kmgs', type_='foreignkey')
    op.drop_column('kmgs', 'fk_company')
    op.drop_constraint(None, 'anakonst', type_='foreignkey')
    op.drop_column('anakonst', 'fk_company')
    op.drop_constraint(None, 'anakomp', type_='foreignkey')
    op.drop_column('anakomp', 'fk_company')
    op.drop_constraint(None, 'ana_mu', type_='foreignkey')
    op.drop_column('ana_mu', 'fk_company')
    # ### end Alembic commands ###
