"""Modcreation und modmod  hinzugefügt

Revision ID: cd5cb1e77693
Revises: 5270b5ca2d2c
Create Date: 2025-05-07 08:29:01.408636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd5cb1e77693'
down_revision: Union[str, None] = '5270b5ca2d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modells', 'modcreation',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('modells', 'modmod',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modells', 'modmod',
               existing_type=sa.DATETIME(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('modells', 'modcreation',
               existing_type=sa.DATETIME(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
