"""fk_user zu components

Revision ID: e0418e840046
Revises: 15425352d93e
Create Date: 2025-05-12 08:58:29.353501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0418e840046'
down_revision: Union[str, None] = '15425352d93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod_components', sa.Column('fk_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mod_components', 'users', ['fk_user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mod_components', type_='foreignkey')
    op.drop_column('mod_components', 'fk_user')
    # ### end Alembic commands ###
