"""Messpunkt_anzahl in Anakomp

Revision ID: ea8f9669f3ac
Revises: fd68a70b7c42
Create Date: 2025-05-08 10:00:47.254058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8f9669f3ac'
down_revision: Union[str, None] = 'fd68a70b7c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anakomp', sa.Column('messpunkt_anzahl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anakomp', 'messpunkt_anzahl')
    # ### end Alembic commands ###
