"""fk_user zu fk_user_id

Revision ID: f410b4138ddb
Revises: e0418e840046
Create Date: 2025-05-12 09:50:26.494479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f410b4138ddb'
down_revision: Union[str, None] = 'e0418e840046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ana_mu', sa.Column('fk_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('ana_mu_ibfk_3', 'ana_mu', type_='foreignkey')
    op.create_foreign_key(None, 'ana_mu', 'users', ['fk_user_id'], ['id'])
    op.drop_column('ana_mu', 'fk_user')
    op.add_column('mod_components', sa.Column('fk_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('mod_components_ibfk_2', 'mod_components', type_='foreignkey')
    op.create_foreign_key(None, 'mod_components', 'users', ['fk_user_id'], ['id'])
    op.drop_column('mod_components', 'fk_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod_components', sa.Column('fk_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mod_components', type_='foreignkey')
    op.create_foreign_key('mod_components_ibfk_2', 'mod_components', 'users', ['fk_user'], ['id'])
    op.drop_column('mod_components', 'fk_user_id')
    op.add_column('ana_mu', sa.Column('fk_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ana_mu', type_='foreignkey')
    op.create_foreign_key('ana_mu_ibfk_3', 'ana_mu', 'users', ['fk_user'], ['id'])
    op.drop_column('ana_mu', 'fk_user_id')
    # ### end Alembic commands ###
