"""add is_builtin

Revision ID: f88d6762ca31
Revises: 04571d401ed8
Create Date: 2026-05-20 14:42:22.988144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88d6762ca31'
down_revision: Union[str, None] = '04571d401ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modells', sa.Column('is_builtin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modells', 'is_builtin')
    # ### end Alembic commands ###
