"""Messpunkt_anzahl in Components

Revision ID: fd68a70b7c42
Revises: 6c1a54116f5b
Create Date: 2025-05-08 09:54:51.005687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd68a70b7c42'
down_revision: Union[str, None] = '6c1a54116f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod_components', sa.Column('messpunkt_anzahl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mod_components', 'messpunkt_anzahl')
    # ### end Alembic commands ###
