export const COMPONENTS: Record<number, string> = {
    1001: "TK_KalibrierungME",
    1002: "TK_ErmittelteMessabweichungME",
    1003: "TK_AufloesungME",
    1005: "TK_Ebenheit_1_2_ME",
    1006: "TK_Ebenheit_1_2_MO",
    1007: "TK_ParallelitaetMessflaechenME",
    1008: "TK_KorrParallelitaet_MO",
    1009: "TK_TempDifferenz_MO_ME",
    1010: "TK_AbweichungMittlereTemp_MO_ME",
    1011: "TK_VerformungMO",
    1012: "TK_Korr_Biegung_ME",
    1013: "TK_RundheitMessflaeche_1_2_MO",
    1014: "TK_Zylindrizitaet_MO_1_2",
    1015: "TK_Korr_Zylin_ME_1_2",
    1016: "TK_Korr_Zylin_GN_1_2",
    1017: "TK_Korr_Rundheit_ME_1_2",
    1018: "TK_Korr_Rundheit_EN_1_2",
    1019: "TK_Korr_Rundheit_GN_1_2",
    1020: "TK_Korr_Ebenheit_1_2",
    1021: "TK_Korr_Parallelitaet_EN",
    1022: "TK_Verformung_MOsph_MEplan",
    1023: "TK_Verformung_MOsph_MEsph",
    1024: "TK_Verformung_MOzyl_MEsph",
    1025: "TK_Aufloesung_ME_Einstell",
    1026: "TK_Abweichung_Nennmass_EN",
    1027: "TK_Kalibrierung_EN",
    1028: "TK_Korr_TempDifferenz_EN_ME",
    1029: "TK_Korr_TempDifferenz_EN_ME_20",
    1031: "TK_Drift_GN",
    1032: "TK_Korr_Abplattung_Messkraft",
    10321: "TK_Korr_Abplattung_Messkraft_ME_MO",
    10322: "TK_Korr_Abplattung_Messkraft_ME_GN",
    1033: "TK_Kalibrierung_Faktor_Kennlinie_ME",
    1034: "TK_Kalibrierung_Parm_Kennlinie_ME",
    1035: "TK_Nichtlinearitaet_Kennlinie_ME",
    1036: "TK_Zeitdrift_ME",
    1037: "TK_Verformung_Differenz_MO_GN",
    1038: "TK_AufloesungMO",
    1039: "TK_AnstellwinkelHebel",
    1040: "TK_Wiederholpraezision",
    1041: "TK_NichtZentrischeAntastung",
    1042: "TK_StreuungMesskraft",
    1043: "TK_AbweichungPoissonKoeffizientMO_EN",
    1044: "TK_AbweichungElastizitaetsModul_MO_EN",
    1045: "TK_Messkraft_3Draht_Methode",
    1046: "TK_KalibrierungMessdraehte",
    1047: "TK_Zylindrizitaet_Messdraehte",
    1048: "TK_GewindeProfilwinkel",
    1049: "TK_Messkraft_2Kugel_Methode",
    1050: "TK_KalibrierungMesskugeln",
    1051: "TK_RundheitMesskugeln",
    1052: "TK_Geradheit_stehender_Schenkel_EN",
    1053: "TK_Geradheit_stehender_Schenkel_MO",
    1054: "TK_Geradheit_liegender_Schenkel_EN",
    1055: "TK_Geradheit_liegender_Schenkel_MO",
    1056: "TK_Neigung_Winkelnormal_EN",
    1057: "TK_Neigung_Messobjekts_MO",
    1059: "TK_Kalibrierung_Geradheit_stehender_Schenkel_EN",
    1060: "TK_Kalibrierung_Geradheit_stehender_Schenkel_MO",
    1061: "TK_Kalibrierung_Geradheit_Hoehenmessgeraets",
    1062: "TK_Geradheitabweichung_Hoehenmessgeraets",
    1063: "TK_Positioniergenauigkeit_Taster_X_Achse",
    1064: "TK_Ebenheit_Messplatte",
    1065: "TK_Kalibrierung_Ebenheit_Messplatte",
    1066: "TK_Geradheit_Schenkelinnenseite",
    1067: "TK_Kalibrierung_Geradheit_Schenkelinnenseite",
    1071: "TK_Strichbreite_EN",
    1072: "TK_Strichbreite_MO",
    1073: "TK_Strichbreite_ME",
    1074: "TK_Winkel_Achsen_MO_ME",
    1075: "TK_Anzahl_Verschiebungen_MO",
    1076: "TK_Kalibrierung_Rechwinkligkeit",
    1077: "TK_Ermittelte_Rechwinkligkeit",
    1078: "TK_Rh_Kalibrierung_Einstellnormal_EN",
    1079: "TK_Rh_Drift_Richtiger_Wert_vom_EN",
    1080: "TK_Rh_Unterschied_Kalibrierort_EN",
    1081: "TK_Rh_Wiederholpraezision_Antastung_MO",
    1082: "TK_Rh_Topografie_MO",
    1083: "TK_Rh_Fuehrungsabweichung",
    1084: "TK_Rh_Drift_Fuehrungsabweichung",
    1085: "TK_Rh_Grundrauschen",
    1086: "TK_Rh_Drift_Grundrauschen",
    1087: "TK_Rh_Verformung_MO",
    1088: "TK_Rh_Abweichung_Tastspitzenradius_vom_Nennwert",
    1089: "TK_Rh_Messunsicherheit_Kalibrierung_Tastspitzenradius",
    1090: "TK_Rh_Unbekannte_systematische_Abweichung",
    1091: "TK_Rh_Kalibrierung_Einstellnormal_EN_TG",
    1092: "TK_Rh_Drift_Richtiger_Wert_von_EN_TG",
    1093: "TK_Rh_Kalibrierort_Kalibrierung_EN_TG",
    1094: "TK_Rh_Wiederholpraezision_Antastung_TG",
    1095: "TK_Rh_Fuehrungsabweichung_TG",
    1096: "TK_Rh_Grundrauschen_TG",
    1097: "TK_Rh_Verformung_EN_TG",
    1098: "TK_Rh_Abweichung_Tastspitzenradius_Nennwert",
    1099: "TK_Rh_Messunsicherheit_Kalibrierung_Tastspitzenradius_TG",
    1100: "TK_Fm_Streuung_Anzeige_ME_in_jedem_Profilpunkt",
    1101: "TK_Fm_Homogenitaet_MO",
    1102: "TK_Fm_Reinigung_MO",
    1103: "TK_Fm_Dynamische_Eingenschaften_ME",
    1104: "TK_Fm_Rauschen_ME",
    1105: "TK_Fm_Streuung_Empfindlichkeit_ME",
    1106: "TK_Fm_Unsicherheit_Vergroesserungsnormal",
    1107: "TK_Fm_Streuung_Spindel_ME",
    1108: "TK_Fm_Linearitaet_ME",
    1109: "TK_Fm_Hysterese_ME",
    1110: "TK_Fm_Exzentrizitaet_MO_Aus",
    1111: "TK_Fm_Exzentrizitaet_MO_Inn",
    1112: "TK_Fm_Nivellierung_Zylinderachse_MO_Rund",
    1113: "TK_Fm_Nivellierung_Zylinderachse_MO_Gerade",
    1114: "TK_Fm_Deformation_MO",
    1115: "TK_Fm_Fuehrungsabweichung_ME",
    1116: "TK_Fm_Temperatur",
    1117: "TK_Fm_Drift_Empfindlichkeit_ME",
    1118: "TK_Fm_Messabweichung_Kalibrierung_ME_Tastsystem",
    1119: "TK_Fm_Kalibrierung_ME_Tastsystem",
    1121: "TK_KTMG_Abstand_system",
    1122: "TK_KTMG_Abstand_zufall",
    1123: "TK_KTMG_Winkel_system",
    1124: "TK_KTMG_Winkel_zufall",
    1125: "TK_KTMG_Winkel_plastVerform",
    1126: "TK_KTMG_Geradheit_system",
    1127: "TK_KTMG_Geradheit_zufall",
    1128: "TK_KTMG_Radius_system",
    1129: "TK_KTMG_Radius_zufall",
    1130: "TK_KTMG_Winkel_Tastspitzenradius",

    1301: "TK_3d_Dw",
    1303: "TK_3d_DeltaDC",
    1304: "TK_3d_DeltaLkmg",
    1310: "TK_3d_DeltaFT",
    1311: "TK_3d_DeltaFkmg",
    1312: "TK_3dA_X1",
    1313: "TK_3dA_W1",
    1314: "TK_3dA_DeltaXT1",
    1315: "TK_3dA_DeltaRT1",
    1316: "TK_3dA_X2",
    1317: "TK_3dA_W2",
    1318: "TK_3dA_DeltaXT2",
    1319: "TK_3dA_DeltaRT2",
    1320: "TK_3dA_DeltaDT",
    1321: "TK_3dA_DeltaDC",
    1322: "TK_3dA_DeltaLKMG",
    1323: "TK_3dA_LalphaM",
    1324: "TK_3dA_LalphaW",
    1325: "TK_3dA_LtM",
    1326: "TK_3dA_LtW",
    1327: "TK_3d_Ri_WE",
    1328: "TK_3d_Ri_DeltaXE1",
    1329: "TK_3d_Ri_DeltaXE2",
    1330: "TK_3d_Ri_DeltaXET1",
    1331: "TK_3d_Ri_DeltaXET2",
    1332: "TK_3d_Ri_WB",
    1333: "TK_3d_Ri_DeltaXB1",
    1334: "TK_3d_Ri_DeltaXB2",
    1335: "TK_3d_Ri_DeltaXBT1",
    1336: "TK_3d_Ri_DeltaXBT2",
    1338: "TK_3d_Ri_DeltaEKMG",
    1339: "TK_3d_Sym_XE1",
    1340: "TK_3d_Sym_WE1",
    1341: "TK_3d_Sym_XE2",
    1342: "TK_3d_Sym_WE2",
    1343: "TK_3d_Sym_DeltaXTE",
    1344: "TK_3d_Sym_XB1",
    1345: "TK_3d_Sym_WB1",
    1346: "TK_3d_Sym_XB2",
    1347: "TK_3d_Sym_WB2",
    1348: "TK_3d_Sym_WB2",
    1349: "TK_3d_Sym_WB2",
    1350: "TK_3d_Koax_XE",
    1351: "TK_3d_Koax_WE",
    1352: "TK_3d_Koax_DeltaXTE",
    1353: "TK_3d_Koax_XB1",
    1354: "TK_3d_Koax_WB1",
    1355: "TK_3d_Koax_XB2",
    1356: "TK_3d_Koax_DeltaXTB",
    1357: "TK_3d_Koax_DeltaEKMG",
    1358: "TK_3d_KoaxGA_XE1",
    1359: "TK_3d_KoaxGA_WE",
    1360: "TK_3d_KoaxGA_XE2",
    1361: "TK_3d_KoaxGA_DeltaXTE",
    1362: "TK_3d_KoaxGA_XB1",
    1363: "TK_3d_KoaxGA_XB2",
    1364: "TK_3d_KoaxGA_DeltaXTB",
    1365: "TK_3d_KoaxGA_DeltaLkmg",
    1368: "TK_3dA_DeltaXTR",
    1371: "TK_3d_Ri_XTER",
    1372: "TK_3d_Ri_XTBR",
    1373: "TK_3d_Sym_DeltaXTR",
    1374: "TK_3d_Koax_DeltaXTR",
    1375: "TK_3d_KoaxGA_DeltaXTR",
    1376: "TK_3d_Ri_Aj",
    1377: "TK_3d_Delta_L_t",
    1378: "TK_3d_ResKMG",
    1379: "TK_3d_Wi_WE",
    1380: "TK_3d_Wi_WB",
    1381: "TK_3d_Wi_DeltaEKMG",
    1391: "TK_3d_PktPkt_dPgeo",
    1392: "TK_3d_PktPkt_dPyKMG",
    1393: "TK_3d_PktPkt_dPZuf",
    1394: "TK_3d_PktPkt_dTaster",
    1395: "TK_3d_PktPkt_dAbwTemp",
    1396: "TK_3d_PktPkt_AbwTempAusd",
    1397: "TK_3d_PktPkt_dFormAbwBE",
    1398: "TK_3d_PktPkt_dFormAbwTE",
    1399: "TK_3d_PktPkt_dWinkelSektor",
};

export const Components: Record<number, string> = {
    1001: "Kalibrierung der Messeinrichtung",
    1002: "Ermittelte Messabweichung bei Kalibrierung ME",
    1003: "Auflösung der ME",
    1005: "Ebenheit ME Fläche 1 und 2",
    1006: "Ebenheit MO Fläche 1 und 2",
    1007: "Parallelität der Messflächen der Messeinrichtung",
    1008: "Parallelität MO",
    1009: "Temperaturdifferenz Messobjekt Messeinrichtung",
    1010: "Abweichung der mittleren Temperatur MO und ME von 20°",
    1011: "Verformung Messobjekt",
    1012: "Aufbiegung ME",
    1013: "Rundheit MO Fläche 1 und 2",
    1014: "Zylindrizität Messobjekt",
    1015: "Zylindrizität ME Flächen 1 und 2",
    1016: "Zylindrizität EN Flächen 1 und 2",
    1017: "Rundheit ME Flächen 1 und 2",
    1018: "Rundheit EN Flächen 1 und 2",
    1019: "",
    1020: "Ebenheit EN Flächen 1 und 2",
    1021: "Parallelität EN",
    1025: "Auflösung ME bei Einstellung",
    1026: "Abweichung vom Nennmaß EN",
    1027: "Kalibrierung Einstellnormal",
    1028: "Temperaturdifferenz zwischen EN und ME",
    1029: "Temperaturdifferenz Mittelwert EN und ME und 20°C",
    1030: "Kalibrierung Einstellnormal (EN)",
    1031: "Drift Einstellnormal (EN)",
    1033: "Kalibrierung Faktor der Kennlinie ME",
    1034: "Kalibrierung Parameter der Kennlinie ME",
    1035: "Nichtlinearität der Kennlinie ME",
    1036: "Zeitdrift ME",
    1037: "Differenz der Verformung MO und EN",
    1038: "Auflösung Messobjekt",
    1039: "Anstellwinkel des Hebels",
    1040: "Wiederholpräzision",
    1041: "Nichtzentrische Antastung",
    1042: "Streuung Messkraft",
    1043: "Abweichung vom mittleren Poissonkoeffizienten MO und ME",
    1044: "Abweichung vom mittleren Elastizitätsmodul MO und EN",
    1045: "Streuung der Messkraft 3-Draht-Methode",
    1046: "Kalibrierung der Messdrähte",
    1047: "Zylindrizität der Messdrähte",
    1048: "Gewindeprofilwinkel",
    1049: "Streuung der Messkraft 2-Kugel-Methode",
    1050: "Kalibrierung der Messkugeln",
    1051: "Rundheit der Messkugeln",
    1052: "Geradheit des stehenden Schenkels des Winkelnormals (EN)",
    1053: "Geradheit des stehenden Schenkels des Messobjekts (MO)",
    1054: "Geradheit des liegenden Schenkels des Winkelnormals (EN)",
    1055: "Geradheit des liegenden Schenkels des Messobjekts (MO)",
    1056: "Neigung des Winkelnormals (EN)",
    1057: "Neigung des Messobjekts (MO)",
    1059: "Kalibrierung Geradheit des stehenden Schenkels (EN)",
    1060: "Kalibrierung Geradheit des stehenden Schenkels (MO)",
    1061: "Kalibrierung Geradheit des Höhenmessgeräts",
    1062: "Geradheitsabweichung des Höhenmessgeräts",
    1063: "Positioniergenauigkeit des Tasters auf der X-Achse",
    1064: "Ebenheit der Messplatte",
    1065: "Kalibrierung der Ebenheit der Messplatte",
    1066: "Geradheit der Schenkelinnenseite",
    1067: "Kalibrierung der Geradheit der Schenkelinnenseite",
    1071: "Strichbreite des EN",
    1072: "Strichbreite des MO",
    1073: "Strichbreite der ME",
    1074: "Winkel der Achsen MO und ME",
    1075: "Anzahl der Verschiebungen des MO",
    1076: "Kalibrierung der Rechtwinkligkeit",
    1077: "Ermittelte Rechtwinkligkeit",
    1078: "Kalibrierung Einstellnormal EN",
    1079: "Drift des richtigen Werts des Einstellnormals EN",
    1080: "Messort bei Kalibrierung EN",
    1081: "Wiederholpräzision der Antastung bei Kalibrierung MO",
    1082: "Topografie des MO",
    1083: "Führungsabweichung ME",
    1084: "Drift der Führungsabweichung ME",
    1085: "Grundrauschen ME",
    1086: "Drift des Grundrauschens ME",
    1087: "Plastische Verformung MO",
    1088: "Abweichung des Tastspitzenradius vom Nennwert",
    1089: "Messunsicherheit der Kalibrierung des Tastspitzenradius",
    1090: "Unbekannte systematische Abweichung",
    1091: "Kalibrierung Einstellnormal EN (TG)",
    1092: "Drift des richtigen Werts des Einstellnormals EN (TG)",
    1093: "Messort bei Kalibrierung EN (TG)",
    1094: "Wiederholpräzision der Antastung des Messobjekts (TG)",
    1095: "Führungsabweichung MO (TG)",
    1096: "Grundrauschen MO (TG)",
    1097: "Plastische Verformung EN (TG)",
    1098: "Abweichung Tastspitzenradius vom Nennwert (TG)",
    1099: "Messunsicherheit der Kalibrierung des Tastspitzenradius (TG)",
    1100: "Streuung der Anzeige der ME in jedem Profilpunkt",
    1101: "Homogenität des MO",
    1102: "Reinigung (Vorbereitung) MO",
    1103: "Dynamische Eigenschaften ME",
    1104: "Rauschen ME",
    1105: "Streuung der Empfindlichkeit der ME",
    1106: "Unsicherheit des Vergrößerungsnormals",
    1107: "Streuung der Spindel von ME",
    1108: "Linearität der ME",
    1109: "Hysterese der ME",
    1110: "Exzentrizität des MO (Außen)",
    1111: "Exzentrizität des MO (Innen)",
    1112: "Nivellierung der Zylinderachse des MO (Rundheit)",
    1113: "Nivellierung der Zylinderachse des MO (Geradheit)",
    1114: "Deformation des Messobjekts",
    1115: "Führungsabweichung der ME",
    1116: "Temperatur",
    1117: "Drift der Empfindlichkeit der ME",
    1118: "Messabweichung bei Kalibrierung der ME (Tastsystem)",
    1119: "Kalibrierung der ME (Tastsystem)",
    1121: "KonturMG Abstandsmessung: systematischer Anteil",
    1122: "KonturMG Abstandsmessung: zufälliger Anteil",
    1123: "KonturMG Winkelmessung: systematischer Anteil",
    1124: "KonturMG Winkelmessung: zufälliger Anteil",
    1125: "KonturMG Winkelmessung: plastische Verformung",
    1126: "KonturMG Geradheitsmessung: systematischer Anteil",
    1127: "KonturMG Geradheitsmessung: zufälliger Anteil",
    1128: "KonturMG Radiusmessung: systematischer Anteil",
    1129: "KonturMG Radiusmessung: zufälliger Anteil",
    1130: "KonturMG Winkelmessung: Tastspitzenradius",
    1301: "Durchmesser des Ausgleichselements am Werkstück",
    1302: "Abweichung des Tasterdurchmessers beim Einmessen des Tasters (Halbkugel)",
    1303: "Abweichung des kalibrierten Durchmessers des Kugelnormals",
    1304: "Geometrieabweichungen des KMG",
    1305: "Abweichung des Ausdehnungskoeffizienten des Maßstabs",
    1306: "Abweichung des Ausdehnungskoeffizienten des Werkstücks",
    1307: "Temperaturabweichung des Maßstabs",
    1308: "Temperaturabweichung des Werkstücks",
    1309: "Angezeigte Formabweichung am Werkstück (Antaststreuung des KMG)",
    1310: "Biegeabweichung des Tasters (Messung am Normal)",
    1311: "Geometrieabweichung des KMG",
    1312: "Koordinate des tolerierten Elements im Schwerpunkt",
    1313: "Winkelabweichung des tolerierten Elements für die Messlänge L(ME)",
    1314: "Abweichung der Mittelpunktkoordinate des Tasters am tolerierten Element",
    1315: "Abweichung des Tasterradius am tolerierten Element (Halbkugel)",
    1316: "Koordinate des Bezugselements im Schwerpunkt",
    1317: "Winkelabweichung des Bezugselements für die Messlänge L(MB)",
    1318: "Abweichung der Mittelpunktkoordinate am Bezugselement vom Einmessen",
    1319: "Abweichung des Tasterdurchmessers am Bezugselement (Halbkugel)",
    1320: "Abweichung des Tasterdurchmessers (Innen- oder Außenmessung selber Taster)",
    1321: "Abweichung des kalibrierten Durchmessers des Kugelnormals (nur bei Oberflächen)",
    1322: "Geometrieabweichung des KMG",
    1323: "Längenkorrektur für Abweichung des Ausdehnungskoeffizienten des Maßstabs",
    1324: "Längenkorrektur für Abweichung des Ausdehnungskoeffizienten des Werkstücks",
    1325: "Längenkorrektur für Temperaturabweichung des Maßstabs",
    1326: "Längenkorrektur für Temperaturabweichung des Werkstücks",
    1327: "Winkelabweichung des tolerierten Elements (entfällt bei gemeinsamer Achse)",
    1328: "Abweichung der Koordinate des 1. tolerierten Elements (nur bei gemeinsamer Achse)",
    1329: "Abweichung der Koordinate des 2. tolerierten Elements (nur bei gemeinsamer Achse)",
    1330: "Abweichung des Tastermittelpunktes des 1. tolerierten Elements (nur bei zwei Tastern)",
    1331: "Abweichung des Tastermittelpunktes des 2. tolerierten Elements (nur bei zwei Tastern)",
    1332: "Winkelabweichung des Bezugselements (entfällt bei gemeinsamer Achse)",
    1333: "Abweichung der Koordinate des 1. Bezugselements (nur bei gemeinsamer Achse)",
    1334: "Abweichung der Koordinate des 2. Bezugselements (nur bei gemeinsamer Achse)",
    1335: "Abweichung des Tastermittelpunktes des 1. Bezugselements (nur bei zwei Tastern)",
    1336: "Abweichung des Tastermittelpunktes des 2. Bezugselements (nur bei zwei Tastern)",
    1337: "Korrektur für die Antaststreuung des KMG (nur bei Gerade und Ebene)",
    1338: "Geometrieabweichung des KMG",
    1339: "Koordinate des ersten tolerierten Elements im Schwerpunkt",
    1340: "Winkelabweichung des ersten tolerierten Elements",
    1341: "Koordinate des zweiten tolerierten Elements im Schwerpunkt",
    1342: "Winkelabweichung des zweiten tolerierten Elements",
    1343: "Mittelpunktabweichung des Tasters des tolerierten Elements (Halbkugel)",
    1344: "Koordinate des ersten Bezugselements im Schwerpunkt",
    1345: "Winkelabweichung des ersten Bezugselements",
    1346: "Koordinate des zweiten Bezugselements im Schwerpunkt",
    1347: "Winkelabweichung des zweiten Bezugselements",
    1348: "Mittelpunktabweichung des Tasters des Bezugselements (Halbkugel)",
    1349: "Geometrieabweichung des KMG",
    1350: "Mittelpunktkoordinate des tolerierten Elements",
    1351: "Winkelabweichung des tolerierten Elements",
    1352: "Mittelpunktabweichung des Tasters des tolerierten Elements (Halbkugel)",
    1353: "Mittelpunktkoordinate des (ersten) Bezugselements",
    1354: "Winkelabweichung des Bezugselements im Bereich der Bezugslänge",
    1355: "Mittelpunktkoordinate des zweiten Bezugselements",
    1356: "Mittelpunktabweichung des Tasters des Bezugselements (Halbkugel)",
    1357: "Geometrieabweichung des KMG",
    1358: "Mittelpunktkoordinate des tolerierten Elements (ist auch Bezugselement)",
    1359: "Winkelabweichung des tolerierten Elements (bei Zylinder und Kegel)",
    1360: "Mittelpunktkoordinate des zweiten tolerierten Elements (bei Messung von zwei Kreisen)",
    1361: "Mittelpunktabweichung des Tasters des tolerierten Elements (Halbkugel)",
    1362: "Mittelpunktkoordinate des Bezugselements (nicht toleriertes Bezugselement)",
    1363: "Mittelpunktkoordinate des zweiten Bezugselements (bei Messung von zwei Kreisen)",
    1364: "Mittelpunktabweichung des Tasters des Bezugselements (Halbkugel)",
    1365: "Geometrieabweichung des KMG",
    1366: "Kegel: Neigungswinkel",
    1367: "Kegel: Abstand der Ebene des Durchmessers vom Schwerpunkt der Messpunkte",
    1368: "Abweichung der Mittelpunktkoordinaten der Taster durch Rotationsabweichungen",
    1369: "Maximale positive Abweichung der Oberfläche (Antaststreuung des KMG) - A(1)",
    1370: "Maximale negative Abweichung der Oberfläche (Antaststreuung des KMG) - A(2)",
    1371: "Abweichung der Tastermittelpunkte am tol. Element durch Rotationsabweichungen",
    1372: "Abweichung der Tastermittelpunkte am Bezugselement durch Rotationsabweichungen",
    1373: "Abweichung der Mittelpunktkoordinaten der Taster durch Rotationsabweichungen",
    1374: "Abweichung der Mittelpunktkoordinaten der Taster durch Rotationsabweichungen",
    1375: "Abweichung der Mittelpunktkoordinaten der Taster durch Rotationsabweichungen",
    1376: "Abweichung eines Oberflächenpunktes",
    1377: "Längenabweichung für die mittlere Temperatur des Werkstücks und Maßstab des KMG",
};

export const tcMapping: Record<number, string> = {
    1: "TC_Messbereich",
    2: "TC_Nennmass",
    3: "TC_UntAbmass",
    4: "TC_ObAbmass",
    5: "TC_Einheit",
    6: "TC_AusdehnKoeffME",
    7: "TC_AusdehnKoeffEN",
    8: "TC_AusdehnKoeffMO",
    9: "TC_DurchmesserMessflaeche",
    10: "TC_DurchmesserMesseinsatzME",
    11: "TC_BreiteMessflaecheMO",
    12: "TC_nicht_benutzt_BreiteMessflaecheGN",
    13: "TC_BreiteMessflaecheEN",
    14: "TC_FaktorKennlinieME",
    15: "TC_ParameterKennlinieME",
    16: "TC_NichtLinearKennlinieME",
    17: "TC_Geometrie_ME",
    18: "TC_Geometrie_MO",
    19: "TC_Geometrie_GN",
    20: "TC_Geometrie_BN",
    21: "TC_MantellinieME",
    22: "TC_MantellinieMO",
    23: "TC_nicht_benutzt_TC_MantellinieGN",
    24: "TC_MantellinieEN",
    25: "TC_Messwert",
    26: "TC_MesskraftME",
    27: "TC_MesskraftSchwankungME",
    28: "TC_NennmassEN",
    29: "TC_nicht_benutzt_TC_NennmassGN",
    30: "TC_TempME",
    31: "TC_TempMO",
    32: "TC_TempEN",
    33: "TC_ZeitDeltaMessungEN_MO",
    34: "TC_ZeitDrift",
    35: "TC_DurchmesserEN",
    36: "TC_Winkelabweichung_von_90_Grad",
    37: "TC_Radius_der_Zone_des_Spiels",
    38: "TC_Laenge_kurze_Kante_PEM",
    39: "TC_Tol_Abw_Spanne_ISO_3650",
    40: "TC_Elast_Modul_Normal",
    41: "TC_Elast_Modul_MO",
    42: "TC_Poisson_Koeff_Normal",
    43: "TC_Poisson_Koeff_MO",
    44: "TC_Korrelationskoeffizient",
    45: "TC_Schrittweite_Geradheitskalibrierung_EN",
    46: "TC_Positionsgenauigkeit_Kalibrierung_MO",
    47: "TC_Betrag_max_Abweichung_Bezugsgerade",
    48: "TC_Laenge_stehender_Schenkel_EN",
    49: "TC_Abstand_Stuetzpunkte_EN",
    50: "TC_Geradheit_Messplatte_EN",
    51: "TC_Positionsabweichung_Stuetzpunkte_EN",
    52: "TC_Kalibrierung_Geradheit_EN",
    53: "TC_Laenge_stehender_Schenkel_MO",
    54: "TC_Stuetzpunktabstand_MO",
    55: "TC_Geradheit_Messplatte_MO",
    56: "TC_Positionsabweichung_Stuetzpunkte_MO",
    57: "TC_Kalibrierung_Geradheit_MO",
    58: "TC_Kalibrierung_Ebenheit_Messplatte",
    59: "TC_Positionsgenauigkeit_Stuetzpunkte",
    60: "TC_Schrittweite_Geradheitskalibrierung_MO",
    61: "TC_Hoehendifferenz_Stuetzpunkte",
    62: "TC_Laenge_Messobjekt",
    63: "TC_Anzahl_Verschiebungen_MO",
    64: "TC_Messbereichsendwert_Messeinrichtung",
    65: "TC_Hoehe_zu_Rechtwinkligkeit",
    66: "TC_Rh_Anzahl_Messwerte_pro_Teilmessstrecke",
    67: "TC_Rh_Anzahl_Teilmessstrecken",
    68: "TC_Rh_Ortabhaengige_Unsicherheit_in_y",
    69: "TC_Rh_Gradient_in_Rillenrichtung",
    70: "TC_Rh_Messpunktabstand",
    71: "TC_Rh_Tiefpasswellenlaengen",
    72: "TC_Rh_Kennwertaenderungsfaktor",
    73: "TC_Rh_Gemessene_Kenngroesse",
    74: "TC_Rh_Anzahl_Wiederholungsmessungen_geaenderter_Antastort",
    75: "TC_Rh_Anzahl_Wiederholmessungen_selber_Antastort",
    76: "TC_Fm_Anzahl_Wiederholmessungen_StreuungAnzeige",
    77: "TC_Fm_Abstand_zwischen_zwei_benachbarten_Profilpunkten",
    78: "TC_Fm_Grenzwellenlaenge",
    79: "TC_Fm_Messwert_MO",
    80: "TC_Fm_Richtiger_Wert_Rundheit_Kugelnormal",
    81: "TC_Fm_Messunsicherheit_der_Kalibrierung_Kugelnormal",
    82: "TC_Fm_Gemessenden_Exzentrizitaet",
    83: "TC_Fm_Aussendurchmesser_MO",
    84: "TC_Fm_Tastkugeldurchmesser",
    85: "TC_Fm_Innendurchmesser_MO",
    86: "TC_Fm_Kippung_MO_XAchse",
    87: "TC_Fm_Kippung_MO_YAchse",
    88: "TC_Fm_Radius_MO",
    89: "TC_Fm_Neigung_Zylinderachse_MO_zu_Flaeche_XOY",
    90: "TC_Fm_Formabweichung_Normal",
    91: "TC_Fm_Kalibrierung_Normal",
    92: "TC_Fm_Standardabweichung_Wiederholmessungen_Normal",
    93: "TC_Fm_AnzahlMessungen_Fuehrungsabweichung",
    94: "TC_Fm_Gemessene_Rundheit_EN",
    95: "TC_KTMG_Gemessener_Abstand",
    96: "TC_KTMG_Konstanter_Anteil_EMPE",
    97: "TC_KTMG_Anzahl_Messpunkte",
    98: "TC_KTMG_Gemessener_Winkel",
    99: "TC_KTMG_Laenge_kleinster_Schenkel",
    100: "TC_KTMG_Gemessene_Geradheit",
    101: "TC_KTMG_Sektor_Kreis",
    102: "TC_3d_KMG_A",
    103: "TC_3d_KMG_K",
    104: "TC_3d_KMG_Uc",
    105: "TC_3d_KMG_alphaM",
    106: "TC_3d_KMG_Tm",
    107: "TC_3d_KMG_deltaTm",
    108: "TC_3d_KMG_alphaW",
    109: "TC_3d_KMG_Tw",
    110: "TC_3d_KMG_deltaTw",
    111: "TC_3d_DUME_D",
    112: "TC_3d_DUME_alpha",
    113: "TC_3d_DUME_l",
    114: "TC_3d_FORM_L",
    115: "TC_3d_FORM_DL",
    116: "TC_3d_FORM_F",
    117: "TC_3d_ABST_L",
    118: "TC_3d_ABST_LM1",
    119: "TC_3d_ABST_LE1",
    120: "TC_3d_ABST_LM2",
    121: "TC_3d_ABST_LE2",
    122: "TC_3d_Ri_LA",
    123: "TC_3d_Ri_Alpha",
    124: "TC_3d_Ri_LME",
    125: "TC_3d_Ri_LE",
    126: "TC_3d_Ri_LMB",
    127: "TC_3d_Sym_DE",
    128: "TC_3d_Sym_LE",
    129: "TC_3d_Sym_DB",
    130: "TC_3d_Sym_LMB",
    131: "TC_3d_Koax_DE",
    132: "TC_3d_Koax_LE",
    133: "TC_3d_Koax_LA",
    134: "TC_3d_Koax_DB",
    135: "TC_3d_Koax_LB",
    136: "TC_3d_Koax_LMB",
    137: "TC_3d_KoaxGA_DE",
    138: "TC_3d_KoaxGA_LME",
    139: "TC_3d_KoaxGA_LE",
    140: "TC_3d_KoaxGA_LB",
    141: "TC_3d_KMG_LT",
    142: "TC_3d_DUME_LM",
    143: "TC_3D_DUME_LS",
    144: "TC_3D_ABST_LTE",
    145: "TC_3D_ABST_LTB",
    146: "TC_3d_Ri_LTE1",
    147: "TC_3d_Ri_LTE2",
    148: "TC_3d_Ri_LTB1",
    149: "TC_3d_Ri_LTB2",
    150: "TC_3d_Sym_LME",
    151: "TC_3d_Sym_LB",
    152: "TC_3d_Sym_LTE",
    153: "TC_3d_Sym_LTB",
    154: "TC_3d_Koax_LME",
    155: "TC_3d_Koax_LT_entfaellt",
    156: "TC_3d_Koax_LTB",
    157: "TC_3d_Koax_LTE",
    158: "TC_3d_KoaxGA_LA",
    159: "TC_3d_KoaxGA_LTB",
    160: "TC_3d_KoaxGA_LTE",
    161: "TC_3d_KMG_MpeML",
    162: "TC_Gewinde_Steigung",
    163: "TC_3D_NennLaenge_LD",
    164: "TC_3d_FORM_FN",
    165: "TC_3d_FORM_FKMG",
    166: "TC_3d_KMG_AUFLOES",
    167: "TC_3d_PktPkt_dist",
    168: "TC_3d_PktPkt_Wechsel",
    169: "TC_3d_PktPkt_nTastBe",
    170: "TC_3d_PktPkt_nTastTe",
    171: "TC_3d_PktPkt_SigBe",
    172: "TC_3d_PktPkt_SigTe",
    173: "TC_3d_PktPkt_ScanKgl",
    174: "TC_3d_PktPkt_MBe",
    175: "TC_3d_PktPkt_Mte",
    176: "TC_3d_PktPkt_Temp",
    177: "TC_3d_PktPkt_Gamma0",
    178: "TC_3d_PktPkt_Gamma1",
    179: "TC_3d_PktPkt_WinkelSeg_BE",
    180: "TC_3d_PktPkt_WinkelSeg_TE",
    181: "TC_3d_PktPkt_AnzSims",
    182: "TC_3d_PktPkt_Dia_BE",
    183: "TC_3d_PktPkt_Dia_TE",
    184: "TC_3d_KMG_AmpX",
    185: "TC_3d_KMG_AmpY",
};

export const prozessMapping: Record<number, string> = {
  1: "Durchmesser",
  2: "Abstand",
  3: "Richtung",
  4: "Koaxialität",
  5: "Form",
  6: "Winkel",
  7: "Position",
};